### ISSUE TITLE
Issue new token if branch is not available, 2nd attempt

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAuth#1005]
There might be a race condition between issuing token for authentication by oxAuth and cleanerJob. 
If cleanerJob clean tokens in the middle of authentication, oxAuth don't get that token when user complete it's authentication and it result something like below: 

```
2019-02-19 10:05:19,951 ERROR [qtp1433867275-2297] [org.xdi.oxauth.model.common.AuthorizationGrant] (AuthorizationGrant.java:169) - Failed to persist entry: uniqueIdentifier=7c9730ac-21d3-4238-b4b0-9cdd4c0a7a88,oxAuthGrantId=16236fb9-efdf-450b-8de4-dae250172858,inum=@!270D.2F71.07C0.8008!0001!376D.E063!0008!20A6.81F7,ou=clients,o=@!270D.2F71.07C0.8008!0001!376D.E063,o=gluu
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to persist entry: uniqueIdentifier=7c9730ac-21d3-4238-b4b0-9cdd4c0a7a88,oxAuthGrantId=16236fb9-efdf-450b-8de4-dae250172858,inum=@!270D.2F71.07C0.8008!0001!376D.E063!0008!20A6.81F7,ou=clients,o=@!270D.2F71.07C0.8008!0001!376D.E063,o=gluu
        at org.gluu.site.ldap.persistence.LdapEntryManager.persist(LdapEntryManager.java:124) ~[oxcore-ldap-3.1.4.sp2.jar:?]
        at org.gluu.site.ldap.persistence.AbstractEntryManager.persist(AbstractEntryManager.java:90) ~[oxcore-ldap-3.1.4.sp2.jar:?]
        at org.gluu.site.ldap.persistence.LdapEntryManager$Proxy$_$$_WeldClientProxy.persist(Unknown Source) ~[oxcore-ldap-3.1.4.sp2.jar:?]
.....
.....
......
Caused by: com.unboundid.ldap.sdk.LDAPException: Entry uniqueIdentifier=7c9730ac-21d3-4238-b4b0-9cdd4c0a7a88,oxAuthGrantId=16236fb9-efdf-450b-8de4-dae250172858,inum=@!270D.2F71.07C0.8008!0001!376D.E063!0008!20A6.81F7,ou=clients,o=@!270D.2F71.07C0.8008!0001!376D.E063,o=gluu cannot be added because its parent entry oxAuthGrantId=16236fb9-efdf-450b-8de4-dae250172858,inum=@!270D.2F71.07C0.8008!0001!376D.E063!0008!20A6.81F7,ou=clients,o=@!270D.2F71.07C0.8008!0001!376D.E063,o=gluu does not exist in the server
        at com.unboundid.ldap.sdk.LDAPConnection.add(LDAPConnection.java:2099) ~[unboundid-ldapsdk-4.0.7.jar:4.0.7]

``` 

This feature request will allow oxAuth to try to issue new token if such scenario appear.

**Comment by yurem** [comment]
Fixed
