### ISSUE TITLE
Fix NPE in RO Grant when client hasn't redirect_uri

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#1034]
## Describe the issue
Instead of throwing NPE application should handle client configuration issue and return expected result to RP.

## Steps To Reproduce
1. Register client without redirect_uri
2. Send RO Grant request to token endpoint

## Root case
```
2019-02-28 12:56:44,202 ERROR [qtp804611486-12] [org.xdi.oxauth.model.common.AuthorizationGrant] (AuthorizationGrant.java:231) - null
java.lang.NullPointerException: null
    at org.xdi.oxauth.model.token.IdTokenFactory.generateSignedIdToken(IdTokenFactory.java:262) ~[classes/:?]
    at org.xdi.oxauth.model.token.IdTokenFactory.createJwr(IdTokenFactory.java:530) ~[classes/:?]
    at org.xdi.oxauth.model.common.AuthorizationGrant.createIdToken(AuthorizationGrant.java:89) ~[classes/:?]
    at org.xdi.oxauth.model.common.AuthorizationGrant.createIdToken(AuthorizationGrant.java:215) [classes/:?]
    at org.xdi.oxauth.token.ws.rs.TokenRestWebServiceImpl.requestAccessToken(TokenRestWebServiceImpl.java:330) [classes/:?]
```

**Comment by sahiliamsso** [comment]
I am getting this error
```
2019-06-20 00:46:04,920 ERROR [qtp985655350-19] [org.gluu.oxauth.service.external.ExternalResourceOwnerPasswordCredentialsService] (ExternalResourceOwnerPasswordCredentialsService.java:61) - null
java.lang.NullPointerException: null
        at org.gluu.oxauth.service.external.ExternalResourceOwnerPasswordCredentialsService.executeExternalAuthenticate(ExternalResourceOwnerPasswordCredentialsService.java:55) ~[classes/:?]
        at org.gluu.oxauth.service.external.ExternalResourceOwnerPasswordCredentialsService.executeExternalAuthenticate(ExternalResourceOwnerPasswordCredentialsService.java:39) ~[classes/:?]
        at org.gluu.oxauth.service.external.ExternalResourceOwnerPasswordCredentialsService$Proxy$_$$_WeldClientProxy.executeExternalAuthenticate(Unknown Source) ~[classes/:?]
        at org.gluu.oxauth.token.ws.rs.TokenRestWebServiceImpl.requestAccessToken(TokenRestWebServiceImpl.java:316) ~[classes/:?]
        at org.gluu.oxauth.token.ws.rs.TokenRestWebServiceImpl$Proxy$_$$_WeldClientProxy.requestAccessToken(Unknown Source) ~[classes/:?]
        at sun.reflect.GeneratedMethodAccessor441.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140) ~[resteasy-jaxrs-3.5.1.Final.jar:3.5.1.Final]
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:510) ~[resteasy-jaxrs-3.5.1.Final.jar:3.5.1.Final]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:401) ~[resteasy-jaxrs-3.5.1.Final.jar:3.5.1.Final]
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:365) ~[resteasy-jaxrs-3.5.1.Final.jar:3.5.1.Final]
        at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:361) ~[resteasy-jaxrs-3.5.1.Final.jar:3.5.1.Final]
```

**Comment by yuriyz** [comment]
Exception above points to line 55 which is blank on latest build, see https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/gluu/oxauth/service/external/ExternalResourceOwnerPasswordCredentialsService.java#L55

Issue is not reproducible on latest build. It seems you have outdated build. Please test on latest build.

Also please use `printVersion.py` prepared by @mbaser to check whether you have latest version or not.

**Comment by qbert2k** [comment]
Hello Sahil, please provide details to reproduce the error.
It seems a configuration issue in your custom scripts, please check.
