### ISSUE TITLE
Remove usages of Filter.create to create string-based filters

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxAuth#1044]
In oxauth there are usages of [this method](https://github.com/GluuFederation/oxCore/blob/master/oxFilter/src/main/java/org/gluu/search/filter/Filter.java#L60) in order to build instances of `Filter` from strings. When using couchbase ad DB [this](https://github.com/GluuFederation/oxCore/blob/master/oxCouchbase/src/main/java/org/gluu/persist/couchbase/impl/CouchbaseFilterConverter.java#L26) will be thrown

Most usages are in package ` org.xdi.oxauth.uma.service`. The following is the trace of how a ticket validation fails:

```
2019-03-24 20:04:30,536 TRACE [qtp804611486-12] [org.xdi.oxauth.uma.service.UmaTokenService] (UmaTokenService.java:90) - requestRpt grant_type: urn:ietf:params:oauth:grant-type:uma-ticket, ticket: e4658816-246f-42e9-8825-f09371bf5122, claim_token: null, claim_token_format: null, pct: null, rpt: null, scope: null
2019-03-24 20:04:30,536 TRACE [qtp804611486-12] [org.xdi.oxauth.uma.service.UmaValidationService] (UmaValidationService.java:230) - Validate grantType: urn:ietf:params:oauth:grant-type:uma-ticket
2019-03-24 20:04:30,537 TRACE [qtp804611486-12] [org.xdi.oxauth.uma.service.UmaPermissionService] (UmaPermissionService.java:142) - Failed to find entries with baseDN: ou=clients,o=@!1DA5.2B0A.FB9B.F2BC!0001!21CA.3123,o=gluu, filter: (&(&(objectClass=top)(objectClass=oxUmaResourcePermission))&(oxTicket=e4658816-246f-42e9-8825-f09371bf5122))
org.gluu.persist.exception.EntryPersistenceException: Failed to find entries with baseDN: ou=clients,o=@!1DA5.2B0A.FB9B.F2BC!0001!21CA.3123,o=gluu, filter: (&(&(objectClass=top)(objectClass=oxUmaResourcePermission))&(oxTicket=e4658816-246f-42e9-8825-f09371bf5122))
	at org.gluu.persist.couchbase.impl.CouchbaseEntryManager.findEntriesImpl(CouchbaseEntryManager.java:365) ~[oxcore-couchbase-4.0.0-SNAPSHOT.jar:?]
	at org.gluu.persist.couchbase.impl.CouchbaseEntryManager.findEntries(CouchbaseEntryManager.java:279) ~[oxcore-couchbase-4.0.0-SNAPSHOT.jar:?]
	at org.gluu.persist.impl.BaseEntryManager.findEntries(BaseEntryManager.java:149) ~[oxcore-persist-4.0.0-SNAPSHOT.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) ~[weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) ~[weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
	at org.gluu.persist.PersistenceEntryManager$378825836$Proxy$_$$_WeldClientProxy.findEntries(Unknown Source) ~[weld-core-impl-3.0.5.Final.jar:?]
	at org.xdi.oxauth.uma.service.UmaPermissionService.getPermissionsByTicket(UmaPermissionService.java:140) [classes/:?]
	at org.xdi.oxauth.uma.service.UmaValidationService.validateTicket(UmaValidationService.java:243) [classes/:?]
	at org.xdi.oxauth.uma.service.UmaTokenService.requestRpt(UmaTokenService.java:94) [classes/:?]
	at org.xdi.oxauth.token.ws.rs.TokenRestWebServiceImpl.requestAccessToken(TokenRestWebServiceImpl.java:115) [classes/:?]
	at org.xdi.oxauth.token.ws.rs.TokenRestWebServiceImpl$Proxy$_$$_WeldClientProxy.requestAccessToken(Unknown Source) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140) [resteasy-jaxrs-3.0.21.Final.jar:3.0.21.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295) [resteasy-jaxrs-3.0.21.Final.jar:3.0.21.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249) [resteasy-jaxrs-3.0.21.Final.jar:3.0.21.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236) [resteasy-jaxrs-3.0.21.Final.jar:3.0.21.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402) [resteasy-jaxrs-3.0.21.Final.jar:3.0.21.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209) [resteasy-jaxrs-3.0.21.Final.jar:3.0.21.Final]
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228) [resteasy-jaxrs-3.0.21.Final.jar:3.0.21.Final]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56) [resteasy-jaxrs-3.0.21.Final.jar:3.0.21.Final]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51) [resteasy-jaxrs-3.0.21.Final.jar:3.0.21.Final]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [servlet-api-3.1.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215) [websocket-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.xdi.oxauth.auth.AuthenticationFilter.processJwtAuth(AuthenticationFilter.java:434) [classes/:?]
	at org.xdi.oxauth.auth.AuthenticationFilter.doFilter(AuthenticationFilter.java:120) [classes/:?]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.xdi.oxauth.audit.debug.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:62) [classes/:?]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.gluu.oxserver.filters.AbstractCorsFilter.handleNonCORS(AbstractCorsFilter.java:362) [oxcore-server-4.0.0-SNAPSHOT.jar:?]
	at org.gluu.oxserver.filters.AbstractCorsFilter.doFilter(AbstractCorsFilter.java:139) [oxcore-server-4.0.0-SNAPSHOT.jar:?]
	at org.xdi.oxauth.filter.CorsFilter.doFilter(CorsFilter.java:110) [classes/:?]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [jetty-security-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.Server.handle(Server.java:503) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: org.gluu.persist.exception.operation.SearchException: Convertion from RAW Ldap filter to couchbasefilter is not implemented
	at org.gluu.persist.couchbase.impl.CouchbaseFilterConverter.convertToLdapFilter(CouchbaseFilterConverter.java:26) ~[oxcore-couchbase-4.0.0-SNAPSHOT.jar:?]
	at org.gluu.persist.couchbase.impl.CouchbaseFilterConverter.convertToLdapFilter(CouchbaseFilterConverter.java:35) ~[oxcore-couchbase-4.0.0-SNAPSHOT.jar:?]
	at org.gluu.persist.couchbase.impl.CouchbaseEntryManager.toCouchbaseFilter(CouchbaseEntryManager.java:593) ~[oxcore-couchbase-4.0.0-SNAPSHOT.jar:?]
	at org.gluu.persist.couchbase.impl.CouchbaseEntryManager.findEntriesImpl(CouchbaseEntryManager.java:356) ~[oxcore-couchbase-4.0.0-SNAPSHOT.jar:?]
	... 72 more
2019-03-24 20:04:30,570 ERROR [qtp804611486-12] [org.xdi.oxauth.uma.service.UmaValidationService] (UmaValidationService.java:245) - Unable to find permissions registered for given ticket:e4658816-246f-42e9-8825-f09371bf5122
2019-03-24 20:04:30,571 DEBUG [qtp804611486-12] [org.xdi.oxauth.model.error.ErrorResponseFactory] (ErrorResponseFactory.java:71) - Looking for the error with id: invalid_ticket
```

Two observations:
- Several methods in `UmaPermissionService` are using `logger.trace` when catching exceptions. Is this appropriate?
- ~~Should we simply remove `create` from `org.gluu.search.filter` ?~~

**Comment by yuriyz** [comment]
I will take over this one

**Comment by yuriyz** [comment]
Fixed in master.
