### ISSUE TITLE
UMA2 scope and resource inaccessible from admin dashboard when associated client has expired

### ISSUE THREAD

**Issue by mstempell** [GluuFederation/oxAuth#1054]
Hello,

Experimenting with UMA2 functionalities of Gluu, i came across a problem.
When an OpenID Connect client gets expired (expiration date reached), the scopes and resources associated with it become inaccessible on the admin dashboard.

Concerning the scope, it just stays the scopes list page when clicking on a scope to access it, but with the URL changing to `https://[VM hostname]/identity/uma/scope.htm?cid=[some incrementing id]`, and `oxthrust.log` gives:
```
2019-04-12 09:02:11,249 DEBUG [qtp1094834071-17] [org.gluu.oxtrust.action.uma.UpdateScopeDescriptionAction] (UpdateScopeDescriptionAction.java:168) - Loading UMA resource '@!F35C.C54C.BE7A.9927!0001!E546.FA55!F1CA.0704'
2019-04-12 09:02:11,274 ERROR [qtp1094834071-17] [org.gluu.oxtrust.action.uma.UpdateScopeDescriptionAction] (UpdateScopeDescriptionAction.java:188) - Failed to find scope description '@!F35C.C54C.BE7A.9927!0001!E546.FA55!F1CA.0704'
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to find entry: inum=@!F35C.C54C.BE7A.9927!0001!E546.FA55!0008!676A.C6A9.FA0F.403C,ou=clients,o=@!F35C.C54C.BE7A.9927!0001!E546.FA55,o=gluu
	at org.gluu.site.ldap.persistence.LdapEntryManager.find(LdapEntryManager.java:306) ~[oxcore-ldap-3.1.4.Final.jar:?]
...
```

Concerning resource, the dashboard gives the `/error` page and `oxthrust.log` gives:
```
2019-04-12 09:11:15,116 DEBUG [qtp1094834071-9] [org.gluu.oxtrust.action.uma.UpdateResourceAction] (UpdateResourceAction.java:155) - Loading UMA resource set 'ef8f5eed-310f-4af6-b9bc-3523156e7dc5'
2019-04-12 09:11:15,129 DEBUG [qtp1094834071-9] [org.gluu.oxtrust.exception.GlobalExceptionHandler] (GlobalExceptionHandler.java:61) - #{updateResourceAction.modify}: org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to find entry: inum=@!F35C.C54C.BE7A.9927!0001!E546.FA55!0008!676A.C6A9.FA0F.403C,ou=clients,o=@!F35C.C54C.BE7A.9927!0001!E546.FA55,o=gluu
javax.faces.FacesException: #{updateResourceAction.modify}: org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to find entry: inum=@!F35C.C54C.BE7A.9927!0001!E546.FA55!0008!676A.C6A9.FA0F.403C,ou=clients,o=@!F35C.C54C.BE7A.9927!0001!E546.FA55,o=gluu
	at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:89) ~[javax.faces-2.2.16.jar:2.2.16]
...
```

So, those scopes and resources cannot be modified or even deleted for clean up from the admin dashboard.

Used Gluu version is CE 3.1.4 (VM installation).

**Comment by mstempell** [comment]
Wrong project actually

**Comment by nynymike** [comment]
Best to register on https://support.gluu.org and post your issues there. Github is only used for bugs or enhancements to the core projects.
