### ISSUE TITLE
Reported by GG: No permissions associated with ticket

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1057]
## Describe the issue

GG fails to gather claims do to validation ticket failure.
```
2019-04-22 10:37:35,440 DEBUG [qtp804611486-14] [org.xdi.oxauth.model.error.ErrorResponseFactory] (ErrorResponseFactory.java:70) - Looking for the error with id: invalid_ticket
2019-04-22 10:37:35,440 DEBUG [qtp804611486-14] [org.xdi.oxauth.model.error.ErrorResponseFactory] (ErrorResponseFactory.java:75) - Found error, id: invalid_ticket
2019-04-22 10:37:35,440 ERROR [qtp804611486-14] [xdi.oxauth.uma.ws.rs.UmaGatheringWS] (UmaGatheringWS.java:125) - Exception happened
org.xdi.oxauth.uma.authorization.UmaWebException: HTTP 302 Found
	at org.xdi.oxauth.uma.service.UmaValidationService.validateTicketWithRedirect(UmaValidationService.java:240) ~[classes/:?]
	at org.xdi.oxauth.uma.ws.rs.UmaGatheringWS.gatherClaims(UmaGatheringWS.java:91) [classes/:?]
	at org.xdi.oxauth.uma.ws.rs.UmaGatheringWS.getGatherClaims(UmaGatheringWS.java:156) [classes/:?]
	at org.xdi.oxauth.uma.ws.rs.UmaGatheringWS$Proxy$_$$_WeldClientProxy.getGatherClaims(Unknown Source) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
```
## Steps To Reproduce
Register UMA ticket and try to use it during Claims Gathering Flow.

**Comment by yuriyz** [comment]
It works by design. Added more logs to oxauth and oxd projects related to UMA ticket renewal. Also added more notes to oxd docs to avoid confusion.
