### ISSUE TITLE
NPE when Resource Owner Password Credentials is not loaded properly

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#1103]
This exception led to errors when RO script not loaded properly. Code should check if script loaded and return false instead throwing NPE.

```
..
2019-06-19 11:38:53,496 DEBUG [qtp985655350-13] [org.gluu.oxauth.service.external.ExternalResourceOwnerPasswordCredentialsService] (ExternalResourceOwnerPasswordCredentialsService.java:
2019-06-19 11:38:53,496 ERROR [qtp985655350-13] [org.gluu.oxauth.service.external.ExternalResourceOwnerPasswordCredentialsService] (ExternalResourceOwnerPasswordCredentialsService.java:
java.lang.NullPointerException: null
at org.gluu.oxauth.service.external.ExternalResourceOwnerPasswordCredentialsService.executeExternalAuthenticate(ExternalResourceOwnerPasswordCredentialsService.java:55) ~[classe
at org.gluu.oxauth.service.external.ExternalResourceOwnerPasswordCredentialsService.executeExternalAuthenticate(ExternalResourceOwnerPasswordCredentialsService.java:39) ~[classe
at org.gluu.oxauth.service.external.ExternalResourceOwnerPasswordCredentialsService$Proxy$_$$_WeldClientProxy.executeExternalAuthenticate(Unknown Source) ~[classes/:?]
...
```

**Comment by yurem** [comment]
![image](https://user-images.githubusercontent.com/6104200/59780619-f9934600-92c2-11e9-82a2-8e464bcba1ef.png)
