### ISSUE TITLE
Key rotation stops to work during logging of expired key.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1128]
## Describe the issue
Rotation stops to work due to wrong reference to key expiration field.
```
org.json.JSONException: JSONObject[“exp”] not a string.
at org.json.JSONObject.getString(JSONObject.java:855) ~[json-20180813.jar:?]
at org.gluu.oxauth.service.KeyGeneratorTimer.updateKeys(KeyGeneratorTimer.java:161) ~[classes/:?]
at org.gluu.oxauth.service.KeyGeneratorTimer.updateKeysImpl(KeyGeneratorTimer.java:136) ~[classes/:?]
at org.gluu.oxauth.service.KeyGeneratorTimer.updateKeys(KeyGeneratorTimer.java:114) ~[classes/:?]
at org.gluu.oxauth.service.KeyGeneratorTimer.process(KeyGeneratorTimer.java:101) [classes/:?]
at org.gluu.oxauth.service.KeyGeneratorTimer$Proxy$_$$_WeldSubclass.process$$super(Unknown Source) [classes/:?]
at sun.reflect.GeneratedMethodAccessor128.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java
:51) [weld-core-impl-3.1.1.Final.jar:3.1.1.Final]
at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-3.1
.1.Final.jar:3.1.1.Final]
at org.gluu.service.cdi.async.AsynchronousInterceptor$1.get(AsynchronousInterceptor.java:36) [oxcore-service-4.0.b2.jar:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_222]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
2019-08-05 13:47:27,509 ERROR [Thread-3467] [org.gluu.oxauth.service.KeyGeneratorTimer] (KeyGeneratorTimer.java:103) - Exception happened wh
ile executing keys update
```

## Steps To Reproduce
1. generated key with expiration time
2. wait until it expires
3. make sure rotation timer run
4. check log and whether keys are rotated.

## Expected behavior
Keys should be rotated, no exception.

## Actual behavior
Not rotated, exception in log.

**Comment by yuriyz** [comment]
Fixed.
