### ISSUE TITLE
oxAuth seem to use wrong connection properties when external LDAP directory is used for authentication

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#1135]
oxAuth doesn't seem to use connection settings for LDAP server supplied at "Manage Authentication" page, and tries to search instance's internal directory using base DN and filter intended for external directory instead

Pre-conditions:

1. Some external LDAP directory to test it against

## Steps To Reproduce

1. Configure Cache Refresh to import some users from the external directory
2. Make sure the import has been conducted successfully
3. On "Manage authentication" page provide required values to configure authentication against the external directory
4. In a separate browser try to log in to oxTrust using one of the users from the external directory

## Actual behavior

1. Logins with imported users always fail
2. `oxauth.log` contains records which look like it tries to search OpenDJ instead of the external dir, while using base DN of the external dir: [full log](https://github.com/GluuFederation/oxAuth/files/3498700/oxauth40b_external_ldap_auth_fails_log.txt)
3. The "Test LDAP connection" button on "Manage LDAP authentication" page works as expected
4. `tcpdump` shows no activity towards the external directory during login attempt, but shows bind request flying there when using the "Test LDAP connection" button 

## Desktop
 - OS: CentOS 7.6.1810
 - Gluu version:  gluu-server-4.0-61-beta1
 - Browser: Chrome, Firefox

**Comment by yuriyz** [comment]
I've checked oxauth and it works. For testing I was forced to modify data directly in LDAP because oxtrust failed to save data to LDAP with error `Failed to update configuration`. 

![image](https://user-images.githubusercontent.com/2013070/63096586-f50fa480-bf76-11e9-9291-26c592973921.png)

@aliaksander-samuseu would you please check whether data are really saved in LDAP by oxtrust ?
You can check it in `oxIDPAuthentication` attribute of `ou=configuration,o=gluu`

![image](https://user-images.githubusercontent.com/2013070/63096675-2d16e780-bf77-11e9-9b67-24e6c61a15eb.png)

As @syntrydy explained it should work on latest oxtrust with latest setup.py (with Rolain changes included).
@aliaksander-samuseu If data are not saved by oxtrust then re-open bug on oxtrust project.

**Comment by sahiliamsso** [comment]
It is still failing but with a different error on Beta3

```
- Getting user information from LDAP: attributeName = 'uid', attributeValue = 'test1'
2019-08-22 01:06:44,361 DEBUG [qtp105704967-18] [org.gluu.oxauth.service.AuthenticationService] (AuthenticationService.java:381) - Searching user by attributes: '[Attribute [name=uid, values=[test1]]]', baseDn: 'o=test'
2019-08-22 01:06:44,364 ERROR [qtp105704967-18] [org.gluu.oxauth.service.AuthenticationService] (AuthenticationService.java:314) - Failed to find entries with baseDN: o=test, filter: (&(&(objectClass=top))(&(uid=test1)))
org.gluu.persist.exception.EntryPersistenceException: Failed to find entries with baseDN: o=test, filter: (&(&(objectClass=top))(&(uid=test1)))
        at org.gluu.persist.ldap.impl.LdapEntryManager.findEntries(LdapEntryManager.java:404) ~[oxcore-persistence-ldap-4.0.b3.jar:?]
        at org.gluu.persist.impl.BaseEntryManager.findEntries(BaseEntryManager.java:153) ~[oxcore-persistence-core-4.0.b3.jar:?]
        at org.gluu.persist.impl.BaseEntryManager.findEntries(BaseEntryManager.java:120) ~[oxcore-persistence-core-4.0.b3.jar:?]
        at org.gluu.oxauth.service.AuthenticationService.getUserByAttribute(AuthenticationService.java:382) ~[classes/:?]
        at org.gluu.oxauth.service.AuthenticationService.authenticate(AuthenticationService.java:283) [classes/:?]
        at org.gluu.oxauth.service.AuthenticationService.externalAuthenticate(AuthenticationService.java:201) [classes/:?]
        at org.gluu.oxauth.service.AuthenticationService.authenticate(AuthenticationService.java:123) [classes/:?]
        at org.gluu.oxauth.service.external.internal.InternalDefaultPersonAuthenticationType.authenticate(InternalDefaultPersonAuthenticationType.java:38) [classes/:?]
        at org.gluu.oxauth.service.external.ExternalAuthenticationService.executeExternalAuthenticate(ExternalAuthenticationService.java:196) [classes/:?]
        at org.gluu.oxauth.service.external.ExternalAuthenticationService$Proxy$_$$_WeldClientProxy.executeExternalAuthenticate(Unknown Source) [classes/:?]
        at org.gluu.oxauth.auth.Authenticator.userAuthenticationInteractive(Authenticator.java:320) [classes/:?]
        at org.gluu.oxauth.auth.Authenticator.authenticateImpl(Authenticator.java:203) [classes/:?]
        at org.gluu.oxauth.auth.Authenticator.authenticate(Authenticator.java:132) [classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at org.apache.el.parser.AstValue.invoke(AstValue.java:247) [org.mortbay.jasper.apache-el-8.5.40.jar:8.5.40]
        at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267) [org.mortbay.jasper.apache-el-8.5.40.jar:8.5.40]
        at org.jboss.weld.module.web.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40) [weld-web-3.1.
```

**Comment by yuriyz** [comment]
@sahiliamsso do you actually have user with `uid=test1` under base dn `o=test`?

Can you show what do you have for this LDAP query ? 
`o=test, filter: (&(&(objectClass=top))(&(uid=test1)))`

**Comment by sahiliamsso** [comment]
```
[root@autoqa bin]# ./ldapsearch --hostname localhost --port 389 --baseDN "o=test" "(&(&(objectClass=top))(&(uid=test1)))"
dn: cn=test1,o=test
objectClass: organizationalPerson
objectClass: top
objectClass: person
objectClass: inetOrgPerson
uid: test1
sn: test1
cn: test1
mail: test1@test.com
givenName: test1

```

**Comment by yuriyz** [comment]
@sahiliamsso oxauth seems to expect `gluuPerson` OC. If you add to this entry `objectClass: gluuPerson` and retry, does it work?

**Comment by yuriyz** [comment]
oxauth expects `gluuPerson` OC. Issue is not reproducible. @sahiliamsso please confirm.
