### ISSUE TITLE
Gluu 4.0 QA - fido2 not working 

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxAuth#1142]
Steps to reproduce:
1. Enable Fido2 custom authentication script and change oxtrust default authentication to use Fido2
2. Login to oxtrust

Expected result: User should be allowed to login with fido2

Actual
After entering credentials, user gets OOPS error, refer screenshot
![image](https://user-images.githubusercontent.com/21104811/60854972-ff988a80-a1cf-11e9-8a40-eb558d50ced0.png)

Error in logs
java:124) - cosePublicKey {"1":2,"3":-7,"-1":1,"-2":"jd5BKlTMD0zCpUz6ZWthh2qp3tUmfa82k2BLVChiKRM=","-3":"tnhmNdRej5UTFCVjYWkz7GjRDGFY9mov5XqFXNxchFA="}
2019-07-04 03:50:39,612 INFO  [qtp985655350-17] [org.gluu.oxauth.fido2.certification.CertificationKeyStoreUtils] (CertificationKeyStoreUtils.java:82) - No metadata for authenticator 77010bd7212a4fc9b236d2ca5e9d4084. Attempting to contact MDS
2019-07-04 03:50:39,613 ERROR [qtp985655350-17] [org.gluu.oxauth.fido2.service.Fido2RpExceptionHandler] (Fido2RpExceptionHandler.java:33) - Handled Fido2 RP exception
org.gluu.oxauth.fido2.exception.Fido2RPRuntimeException: Authenticator not in TOC aaguid 77010bd7-212a-4fc9-b236-d2ca5e9d4084
        at org.gluu.oxauth.fido2.service.mds.MdsService.fetchMetadata(MdsService.java:91) ~[oxauth-fido2-server-4.0.0-SNAPSHOT.jar:?]
        at org.gluu.oxauth.fido2.service.mds.MdsService$Proxy$_$$_WeldClientProxy.fetchMetadata(Unknown Source) ~[oxauth-fido2-server-4.0.0-SNAPSHOT.jar:?]
        at org.gluu.oxauth.fido2.certification.CertificationKeyStoreUtils.getCertificates(CertificationKeyStoreUtils.java:83) ~[oxauth-fido2-server-4.0.0-SNAPSHOT.jar:?]
        at org.gluu.oxauth.fido2.certification.CertificationKeyStoreUtils.populateTrustManager(CertificationKeyStoreUtils.java:97) ~[oxauth-fido2-server-4.0.0-SNAPSHOT.jar:?]
        at org.gluu.oxauth.fido2.certification.CertificationKeyStoreUtils$Proxy$_$$_WeldClientProxy.populateTrustManager(Unknown Source) ~[oxauth-fido2-server-4.0.0-SNAPSHOT.jar:?]
        at org.gluu.oxauth.fido2.service.processors.impl.PackedAttestationProcessor.process(PackedAttestationProcessor.java:84) ~[oxauth-fido2-server-4.0.0-SNAPSHOT.jar:?]
        at org.gluu.oxauth.fido2.service.processors.impl.PackedAttestationProcessor$Proxy$_$$_WeldClientProxy.process(Unknown Source) ~[oxauth-fido2-server-4.0.0-SNAPSHOT.jar:?]
        at org.gluu.oxauth.fido2.service.verifier.AuthenticatorAttestationVerifier.verifyAuthenticatorAttestationResponse(AuthenticatorAttestationVerifier.java:85) ~[oxauth-fido2-server-4.0.0-SNAPSHOT.jar:?]
        at org.gluu.oxauth.fido2.service.verifier.AuthenticatorAttestationVerifier$Proxy$_$$_WeldClientProxy.verifyAuthenticatorAttestationResponse(Unknown Source) ~[oxauth-fido2-server-4.0.0-SNAPSHOT.jar:?]

Fido2 Key Used: Biopass Fetia https://www.ftsafe.com/onlinestores/product?id=3
Gluu 4.0 Centos7.3 couchbase db

**Comment by maduvena** [comment]
[2019_08_29.jetty.log](https://github.com/GluuFederation/oxAuth/files/3553942/2019_08_29.jetty.log)
[oxauth_script.log](https://github.com/GluuFederation/oxAuth/files/3553943/oxauth_script.log)

My observations are as follows - 
1. Enrollment - no problem
2. Authentication - does not get through

**Comment by sahiliamsso** [comment]
Issue still exists in beta4, I get error on second time login

**Comment by sahiliamsso** [comment]
Also, FIDO2 showing up for all users even though it was registered for one user. Can you please check.
![image](https://user-images.githubusercontent.com/21104811/64386623-a39f8600-d007-11e9-8b0f-7a45fd32c926.png)

**Comment by yurem** [comment]
I think this old issue fixed already
