### ISSUE TITLE
Public and private parts of oxAuth keys don't match

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#1152]
Version: gluu-server-4.0-78.beta4.centos7

Description:
Aliases in JSON of `oxAuthConfWebKeys` attribute in LDAP mismatch ones in `/etc/certs/oxauth-keys.jks` file.

1. This line will return keys in LDAP: `# /opt/opendj/bin/ldapsearch -h 127.0.0.1 -p 1636 -Z -X  -s sub -D 'cn=directory manager' -b 'o=gluu' -w 'LDAP_PASS'  '&(objectclass=oxauthconfiguration)' oxAuthConfWebKeys | grep -v 'dn\:\ ' | cut -d' ' -f2 | python -m json.tool | grep -i '\"kid\"\:' | sort`

2. This line returns keys in JKS: `# keytool -list -v -keystore /etc/certs/oxauth-keys.jks -storepass JKS_PASS | grep -i alias | sort`

## Expected behavior
Number of kid-s in LDAP matches number of keys in JKS file. There is one to one match for every kid in the JKS

## Actual behavior
JKS contains more than 2 times fewer keys than published by oxAuth:
```
Alias name: 10c2bcd6-54c4-456e-9056-46436734f2c1_sig_ps384
Alias name: 14f50e8c-5853-4fa0-ac17-915fde34b79d_sig_es256
Alias name: 29b0274a-30a0-434b-82c8-9985fba8e61d_sig_es512
Alias name: 59c60424-452a-4e8e-a099-94c83f524997_sig_ps256
Alias name: 739a4883-d1d3-4c29-921d-5107c4ff39a3_sig_es384
Alias name: 74d2a740-9c0a-41b9-ab57-0438bd173593_sig_ps512
Alias name: 7b0dc694-d07b-4281-b6aa-5ad377080785_sig_rs256
Alias name: 8c3490d6-25ab-41db-9a0f-c75ac31cddae_sig_rs512
Alias name: e64b6dc4-d66a-4c64-b774-868a036e4c68_sig_rs384
```

VS

```
            "kid": "10c2bcd6-54c4-456e-9056-46436734f2c1_sig_ps384",
            "kid": "14f50e8c-5853-4fa0-ac17-915fde34b79d_sig_es256",
            "kid": "29b0274a-30a0-434b-82c8-9985fba8e61d_sig_es512",
            "kid": "2a4f996d-3374-4804-b4c1-44c66a317546_sig_rs256",
            "kid": "3199c41f-218d-4553-b700-26878ae2bdd7_sig_es512",
            "kid": "33a8038c-360c-4590-a14b-a67ccf8cc66b_sig_rs256",
            "kid": "38acc336-bab8-4a67-8ee6-fdc69179b27c_sig_rs256",
            "kid": "59c60424-452a-4e8e-a099-94c83f524997_sig_ps256",
            "kid": "5d88f6f7-5c7f-49b7-9f00-b4bb0529684f_sig_ps384",
            "kid": "67132c0b-a58c-414c-8bd7-71e7bd0ea18a_sig_rs512",
            "kid": "739a4883-d1d3-4c29-921d-5107c4ff39a3_sig_es384",
            "kid": "739bf7dd-438e-4d01-8e86-1e99689d5275_sig_ps256",
            "kid": "74d2a740-9c0a-41b9-ab57-0438bd173593_sig_ps512",
            "kid": "7b0dc694-d07b-4281-b6aa-5ad377080785_sig_rs256",
            "kid": "8c3490d6-25ab-41db-9a0f-c75ac31cddae_sig_rs512",
            "kid": "8ec384ef-f498-4b53-b682-a2a29d1f5875_sig_es384",
            "kid": "98faa98d-1f89-4c2b-a051-2bf0205ea19d_sig_rs256",
            "kid": "a952ee14-2ba5-404f-bbb8-161554cd9eb9_sig_rs256",
            "kid": "cb879298-1d3f-472a-8485-857f9911b5c3_sig_rs384",
            "kid": "cba5cf8b-bcd5-4d90-8081-9e513d0d9fc6_sig_ps512",
            "kid": "e64b6dc4-d66a-4c64-b774-868a036e4c68_sig_rs384",
            "kid": "f244a733-8522-4d80-9822-456f3a6a0c6a_sig_es256",
```

Some kid-s can't be looked up in JSK ("2a4f996d-3374-4804-b4c1-44c66a317546_sig_rs256" for example).

This currently results in server error if a client needs `RS256` method to sign `id_token`

```
2019-09-12 16:18:22,272 ERROR [qtp1359044626-18] [org.gluu.oxauth.model.crypto.OxAuthCryptoProvider] (OxAuthCryptoProvider.java:211) - Failed to find private key by kid: null, signatureAlgorithm: RS256(check whether web keys JSON in persistence corresponds to keystore file.)
2019-09-12 16:18:22,272 ERROR [qtp1359044626-18] [org.gluu.oxauth.model.common.AuthorizationGrant] (AuthorizationGrant.java:266) - Failed to find private key by kid: null, signatureAlgorithm: RS256(check whether web keys JSON in persistence corresponds to keystore file.)
java.lang.RuntimeException: Failed to find private key by kid: null, signatureAlgorithm: RS256(check whether web keys JSON in persistence corresponds to keystore file.)
	at org.gluu.oxauth.model.crypto.OxAuthCryptoProvider.sign(OxAuthCryptoProvider.java:212) ~[oxauth-model-4.0.0-SNAPSHOT.jar:?]
	at org.gluu.oxauth.model.crypto.AbstractCryptoProvider$Proxy$_$$_WeldClientProxy.sign(Unknown Source) ~[oxauth-model-4.0.0-SNAPSHOT.jar:?]
	at org.gluu.oxauth.model.token.JwtSigner.sign(JwtSigner.java:86) ~[classes/:?]
	at org.gluu.oxauth.model.token.IdTokenFactory.generateSignedIdToken(IdTokenFactory.java:288) ~[classes/:?]
	at org.gluu.oxauth.model.token.IdTokenFactory.createJwr(IdTokenFactory.java:530) ~[classes/:?]
	at org.gluu.oxauth.model.common.AuthorizationGrant.createIdToken(AuthorizationGrant.java:96) ~[classes/:?]
	at org.gluu.oxauth.model.common.AuthorizationGrant.createIdToken(AuthorizationGrant.java:251) ~[classes/:?]

                    ....

```

**Comment by yuriyz** [comment]
Fixed, @aliaksander-samuseu please validate on new build.

**Comment by sanjal** [comment]
Gentlemen:
has hit this issue recently in Gluu 4.0-rc1 - if this issue is closed, when to await next release of Gluu or is it possible to patch existing installation?

**Comment by yuriyz** [comment]
Official release should occur in next few days. Package `gluu-server_4.0~bionic_amd64.deb` is in repo so you are welcome to take it.
