### ISSUE TITLE
Gluu 4.0 QA | Openid - Include Claims In Id Token returns error for email 

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxAuth#1156]
## Describe the issue
When "Include Claims In Id Token" is enabled for client, and claim is set as email. then authorize end point returns 500 error

## Steps To Reproduce
1. Create a client with valid Redirect Login URI, Scopes [email, openid, lastname], Response Types and Grant type
2. Go to advanced settings tab, and check "Include Claims In Id Token" radio button
3. Send request 
```
https://<host>/oxauth/restv1/authorize?response_type=code+id_token&client_id=<clientid>&redirect_uri=https://localhost&state=af0ifjsldkjj&scope=openid+email+lastname&nonce=af0ifjsldkjj
```
## Expected behavior
should return code and id token

## Actual behavior
HTTP ERROR 500

 - Environment: CentOS 7.6 4.0 RC1 with couchbase

oxauth logs
```
2019-09-18 01:03:23,361 TRACE [qtp105704967-11] [gluu.oxauth.model.crypto.binding.TokenBindingMessage] (TokenBindingMessage.java:57) - TokenBindingMessage present: false, rpCnfKey:
2019-09-18 01:03:24,112 ERROR [qtp105704967-11] [org.gluu.oxauth.model.common.AuthorizationGrant] (AuthorizationGrant.java:266) - java.lang.Boolean cannot be cast to java.lang.String
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
        at org.gluu.oxauth.model.token.IdTokenFactory.getClaims(IdTokenFactory.java:576) ~[classes/:?]
        at org.gluu.oxauth.model.token.IdTokenFactory.generateSignedIdToken(IdTokenFactory.java:178) ~[classes/:?]
        at org.gluu.oxauth.model.token.IdTokenFactory.createJwr(IdTokenFactory.java:530) ~[classes/:?]
        at org.gluu.oxauth.model.common.AuthorizationGrant.createIdToken(AuthorizationGrant.java:96) ~[classes/:?]
        at org.gluu.oxauth.model.common.AuthorizationGrant.createIdToken(AuthorizationGrant.java:251) ~[classes/:?]
        at org.gluu.oxauth.authorize.ws.rs.AuthorizeRestWebServiceImpl.requestAuthorization(AuthorizeRestWebServiceImpl.java:595) ~[classes/:?]
        at org.gluu.oxauth.authorize.ws.rs.AuthorizeRestWebServiceImpl.requestAuthorizationGet(AuthorizeRestWebServiceImpl.java:133) ~[classes/:?]
        at org.gluu.oxauth.authorize.ws.rs.AuthorizeRestWebServiceImpl$Proxy$_$$_WeldClientProxy.requestAuthorizationGet(Unknown Source) ~[classes/:?]
        at sun.reflect.GeneratedMethodAccessor321.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140) ~[resteasy-jaxrs-3.5.1.Final.jar:3.5.1.Final]

```

**Comment by yurem** [comment]
Fixed
