### ISSUE TITLE
Support domain cookie option in session cookies

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#1209]
ROPC + Interception script allows to provide session_id cookie for RP.

RP can set this cookie using cookie header like ``Set-Cookie: session_id=session_id; domain=*.xyz.org; Path=/; Secure; HttpOnly; Expires=Fri, 08 Nov 2030 18:52:39 +0000; HttpOnly"

This flow will create SSO flow. But logout in oxAuth is not work well becuase it's domain cookie.

We need to add new oxAuth option to use domain cookie when this property is not empty.

**Comment by yuriyz** [comment]
I'm not sure how it should play together. Interception script returns to RP `session_id` value. RP here is client, it's not server, it can't set cookie for server via `Set-Cookie` header. It can only send it as client via `Cookie: session_id=blabla`. Browser will not do that, it can be emulated by back-channel call (e.g. `java httpclient`). Here if I got correctly goal is to set up SSO cookie for browser (front-channel call). Workaround is to introduce custom endpoint on OP side (probably from session API) which will allow to set up cookie (via `Set-Cookie` header) if such session exists and we know in advance that it's created by custom script. This is if we want to set up SSO by back-channel custom script.

Re: logout, in case we don't need SSO but just need to clean session we can pass session_id explicitly as parameter to End Session Endpoint `/end_session?session_id=blabla`.

**Comment by yurem** [comment]
I will send link to working demo with ROPC+INteception scrit in private chat

In your flow this step browser should call to set this cookie:
```
RP calls /session (new endpoint which does not exist yet) with session_id. And OP (after validation) sets cookie for it. (front-channel)
```

It's not mandatory step if we will add support domain option in cookie.

**Comment by yuriyz** [comment]
Nice demo, yes, it's not mandatory, RP can call itself. End Session doesn't work because `permissionGrantedMap` is null for session created by RO PW script.

```
java.lang.NullPointerException: null
        at org.gluu.oxauth.session.ws.rs.EndSessionRestWebServiceImpl.auditLogging(EndSessionRestWebServiceImpl.java:397) ~[classes/:?]
        at org.gluu.oxauth.session.ws.rs.EndSessionRestWebServiceImpl.requestEndSession(EndSessionRestWebServiceImpl.java:102) ~[classes/:?]
        at org.gluu.oxauth.session.ws.rs.EndSessionRestWebServiceImpl$Proxy$_$$_WeldClientProxy.requestEndSession(Unknown Source) ~[classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140) ~[resteasy-jaxrs-3.5.1.Final.jar:3.5.1.Final]
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:510) ~[resteasy-jaxrs-3.5.1.Final.jar:3.5.1.Final]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:401) ~[resteasy-jaxrs-3.5.1.Final.jar:3.5.1.Final]
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:365) ~[resteasy-jaxrs-3.5.1.Final.jar:3.5.1.Final]
        at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:361) ~[resteasy-jaxrs-3.5.1.Final.jar:3.5.1.Final]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:367) ~[resteasy-jaxrs-3.5.1.Final.jar:3.5.1.Final]
```

**Comment by yuriyz** [comment]
Fixed 2 NPE and now it works. If don't modify current RO PW script then End Session Endpoint will remove session and will return error with code `post_logout_uri_not_associated_with_client` which RP has to handle
```
{"reason":"Session was removed successfully but post_logout_redirect_uri validation fails since AS failed to validate it against clients associated with session (which was just removed).","error_description":"The provided post logout uri is not associated with client.","error":"post_logout_uri_not_associated_with_client"}
```
Because it can't validate `post_logout_redirect_uri`. 
If we want to avoid it then RO PW script should also have this line 
```
session.addPermission(clientId, true).
```

This line will add client into session permission map, so if then feed `post_logout_redirect_uri` during `/end_session` call then RP will be redirected to that uri.
