### ISSUE TITLE
Latest release of Java 8 (8.252) breaks oxAuth.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1320]
## Describe the issue
latest release of Java 8 (8.252) breaks oxAuth.

It looks like the class org.gluu.oxauth.model.crypto.AbstractCryptoProvider is using sun.security.rsa.RSAPublicKeyImpl which is an internal non-API library class that no longer works as of Java 8.252....
``
2020-04-17 15:08:20.908:WARN:oejs.HttpChannel:qtp475266352-16: /oxauth/restv1/token java.lang.NoSuchMethodError: sun.security.rsa.RSAPublicKeyImpl.<init>(Ljava/math/BigInteger;Ljava/math/BigInteger;)V at org.gluu.oxauth.model.crypto.AbstractCryptoProvider.getPublicKey(AbstractCryptoProvider.java:208) at org.gluu.oxauth.model.crypto.OxAuthCryptoProvider.verifySignature(OxAuthCryptoProvider.java:278) at org.gluu.oxauth.model.crypto.AbstractCryptoProvider$Proxy$_$$_WeldClientProxy.verifySignature(Unknown Source) at org.gluu.oxauth.model.token.ClientAssertion.load(ClientAssertion.java:114) at org.gluu.oxauth.model.token.ClientAssertion.<init>(ClientAssertion.java:45) at org.gluu.oxauth.auth.AuthenticationFilter.processJwtAuth(AuthenticationFilter.java:406) at org.gluu.oxauth.auth.AuthenticationFilter.doFilter(AuthenticationFilter.java:120) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604) at org.gluu.oxauth.audit.debug.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:67) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604) at org.gluu.server.filters.AbstractCorsFilter.handleNonCORS(AbstractCorsFilter.java:362) at org.gluu.server.filters.AbstractCorsFilter.doFilter(AbstractCorsFilter.java:139) at org.gluu.oxauth.filter.CorsFilter.doFilter(CorsFilter.java:110) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604) at com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter.doFilter(WebRequestTrack`
```

**Comment by yuriyz** [comment]
Fixed in 4.1.1.
