### ISSUE TITLE
NotImplementedError in oxauth_script.log for person authentication scripts

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxAuth#1362]
Tried several (PersonAuthentication) custom scripts in 4.2BETA. At every authentication step the following exception appears in oxauth_Script log:

```
2020-05-18 14:37:26,518 ERROR [qtp956420404-12] [org.gluu.oxauth.service.external.ExternalAuthenticationService] (ExternalAuthenticationService.java:226) - NotImplementedError: 'PersonAuthentication' object does not implement abstract method 'getNextStep' from 'org.gluu.model.custom.script.type.auth.PersonAuthenticationType'
org.python.core.PyException: NotImplementedError: 'PersonAuthentication' object does not implement abstract method 'getNextStep' from 'org.gluu.model.custom.script.type.auth.PersonAuthenticationType'
	at org.python.core.Py.NotImplementedError(Py.java:140) ~[jython-standalone-2.7.2.jar:2.7.2]
	at org.python.compiler.ProxyCodeHelpers.notImplementedAbstractMethod(ProxyCodeHelpers.java:97) ~[jython-standalone-2.7.2.jar:2.7.2]
	at org.python.proxies.__main__$PersonAuthentication$7.getNextStep(Unknown Source) ~[?:?]
	at org.gluu.oxauth.service.external.ExternalAuthenticationService.getNextStep(ExternalAuthenticationService.java:224) ~[classes/:?]
	at org.gluu.oxauth.service.external.ExternalAuthenticationService$Proxy$_$$_WeldClientProxy.getNextStep(Unknown Source) ~[classes/:?]
	at org.gluu.oxauth.auth.Authenticator.userAuthenticationInteractive(Authenticator.java:345) ~[classes/:?]
	at org.gluu.oxauth.auth.Authenticator.authenticateImpl(Authenticator.java:207) ~[classes/:?]
	at org.gluu.oxauth.auth.Authenticator.authenticate(Authenticator.java:132) ~[classes/:?]
```

**Comment by yurem** [comment]
It should be fixed in latest build
