### ISSUE TITLE
BUG : Select account functionality is broken 

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1419]
BUG : Select account functionality is broken 

```
javax.faces.FacesException: //opt/jetty-9.4/temp/jetty-localhost-8081-oxauth.war-_oxauth-any-4427990212386226242.dir/webapp/selectAccount.xhtml @9,73 value="#{selectAccountAction.scope}": T
arget Unreachable, identifier [selectAccountAction] resolved to null
        at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:85) ~[javax.faces-2.4.0.jar:2.4.0]
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100) [javax.faces-2.4.0.jar:2.4.0]
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:201) [javax.faces-2.4.0.jar:2.4.0]
        at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:731) [javax.faces-2.4.0.jar:2.4.0]
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:475) [javax.faces-2.4.0.jar:2.4.0]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:876) [jetty-servlet-9.4.19.v20190610.jar:9.4.19.v20190610]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623) [jetty-servlet-9.4.19.v20190610.jar:9.4.19.v20190610]
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214) [websocket-server-9.4.19.v20190610.jar:9.4.19.v20190610]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610) [jetty-servlet-9.4.19.v20190610.jar:9.4.19.v20190610]
        at org.gluu.oxauth.audit.debug.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:67) [classes/:?]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602) [jetty-servlet-9.4.19.v20190610.jar:9.4.19.v20190610]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540) [jetty-servlet-9.4.19.v20190610.jar:9.4.19.v20190610]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146) [jetty-server-9.4.19.v20190610.jar:9.4.19.v20190610]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [jetty-security-9.4.19.v20190610.jar:9.4.19.v20190610]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.19.v20190610.jar:9.4.19.v20190610]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257) [jetty-server-9.4.19.v20190610.jar:9.4.19.v20190610]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711) [jetty-server-9.4.19.v20190610.jar:9.4.19.v20190610]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) [jetty-server-9.4.19.v20190610.jar:9.4.19.v20190610]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347) [jetty-server-9.4.19.v20190610.jar:9.4.19.v20190610]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) [jetty-server-9.4.19.v20190610.jar:9.4.19.v20190610]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480) [jetty-servlet-9.4.19.v20190610.jar:9.4.19.v20190610]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678) [jetty-server-9.4.19.v20190610.jar:9.4.19.v20190610]

```

**Comment by yuriyz** [comment]
Fixed it in master, fix for 4.2.1 was pushed already here https://github.com/GluuFederation/oxAuth/commit/db7a1a302a4cc173a085737adf3eb9f07fb45ea7
