### ISSUE TITLE
oxAuth tries to find session entry which led to exception

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#1466]
Exception:
```
20-09-10 16:13:16,400 ERROR [qtp1989335500-427] [org.gluu.oxauth.service.SessionIdService] (SessionIdService.java:757) - Failed to get session by dn: oxId=e6275316-dc06-4bb7-a236-e9098e85895a,ou=sessions,o=gluu
org.gluu.persist.exception.EntryPersistenceException: Failed to find entry: oxId=e6275316-dc06-4bb7-a236-e9098e85895a,ou=sessions,o=gluu
        at org.gluu.persist.couchbase.impl.CouchbaseEntryManager.find(CouchbaseEntryManager.java:360) ~[oxcore-persistence-couchbase-4.2.1-SNAPSHOT.jar:?]
        at org.gluu.persist.impl.BaseEntryManager.find(BaseEntryManager.java:624) ~[oxcore-persistence-core-4.2.1-SNAPSHOT.jar:?]
        at org.gluu.persist.impl.BaseEntryManager.find(BaseEntryManager.java:504) ~[oxcore-persistence-core-4.2.1-SNAPSHOT.jar:?]
        at org.gluu.persist.impl.BaseEntryManager.find(BaseEntryManager.java:491) ~[oxcore-persistence-core-4.2.1-SNAPSHOT.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor50.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) ~[weld-core-impl-3.1.4.Final.jar:3.1.4.Final]
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) ~[weld-core-impl-3.1.4.Final.jar:3.1.4.Final]
        at org.gluu.persist.EntityManager$PersistenceEntryManager$1948487569$Proxy$_$$_WeldClientProxy.find(Unknown Source) ~[weld-core-impl-3.1.4.Final.jar:?]
        at org.gluu.oxauth.service.SessionIdService.getSessionByDn(SessionIdService.java:751) ~[classes/:?]
        at org.gluu.oxauth.service.SessionIdService.getSessionByDn(SessionIdService.java:728) ~[classes/:?]
        at org.gluu.oxauth.service.SessionIdService.getSessionById(SessionIdService.java:723) ~[classes/:?]
        at org.gluu.oxauth.service.SessionIdService.getSessionId(SessionIdService.java:782) ~[classes/:?]
        at org.gluu.oxauth.service.SessionIdService$Proxy$_$$_WeldClientProxy.getSessionId(Unknown Source) ~[classes/:?]
        at org.gluu.oxauth.service.CookieService.removeOutdatedCurrentSessions(CookieService.java:130) ~[classes/:?]
        at org.gluu.oxauth.service.CookieService.addCurrentSessionCookie(CookieService.java:109) ~[classes/:?]
        at org.gluu.oxauth.service.CookieService.createSessionIdCookie(CookieService.java:236) ~[classes/:?]
        at org.gluu.oxauth.service.SessionIdService.setSessionIdStateAuthenticated(SessionIdService.java:521) ~[classes/:?]
        at org.gluu.oxauth.service.SessionIdService$Proxy$_$$_WeldClientProxy.setSessionIdStateAuthenticated(Unknown Source) ~[classes/:?]
        at org.gluu.oxauth.service.AuthenticationService.configureSessionUser(AuthenticationService.java:609) ~[classes/:?]
        at org.gluu.oxauth.auth.Authenticator.userAuthenticationInteractive(Authenticator.java:434) ~[classes/:?]
        at org.gluu.oxauth.auth.Authenticator.authenticateImpl(Authenticator.java:205) ~[classes/:?]
        at org.gluu.oxauth.auth.Authenticator.authenticate(Authenticator.java:128) ~[classes/:?]
        at jdk.internal.reflect.GeneratedMethodAccessor271.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.apache.el.parser.AstValue.invoke(AstValue.java:247) ~[org.mortbay.jasper.apache-el-8.5.40.jar:8.5.40]
        at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267) ~[org.mortbay.jasper.apache-el-8.5.40.jar:8.5.40]
        at org.jboss.weld.module.web.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40) ~[weld-web-3.1.4.Final.jar:3.1.4.Final]
        at org.jboss.weld.module.web.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50) ~[weld-web-3.1.4.Final.jar:3.1.4.Final]
        at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:65) ~[jakarta.faces-2.3.14.jar:2.3.14]
        at com.sun.faces.application.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:66) ~[jakarta.faces-2.3.14.jar:2.3.14]
        at com.sun.faces.application.ActionListenerImpl.getNavigationOutcome(ActionListenerImpl.java:82) ~[jakarta.faces-2.3.14.jar:2.3.14]
        at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:71) ~[jakarta.faces-2.3.14.jar:2.3.14]
        at javax.faces.component.UICommand.broadcast(UICommand.java:222) ~[jakarta.faces-2.3.14.jar:2.3.14]
        at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:847) ~[jakarta.faces-2.3.14.jar:2.3.14]
        at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1396) ~[jakarta.faces-2.3.14.jar:2.3.14]
        at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:58) ~[jakarta.faces-2.3.14.jar:2.3.14]
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76) ~[jakarta.faces-2.3.14.jar:2.3.14]
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177) ~[jakarta.faces-2.3.14.jar:2.3.14]
        at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707) ~[jakarta.faces-2.3.14.jar:2.3.14]
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451) ~[jakarta.faces-2.3.14.jar:2.3.14]
        at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1395) ~[jetty-servlet-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755) ~[jetty-servlet-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617) ~[jetty-servlet-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226) ~[websocket-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604) ~[jetty-servlet-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.gluu.oxauth.audit.debug.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:67) ~[classes/:?]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1596) ~[jetty-servlet-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545) ~[jetty-servlet-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590) ~[jetty-security-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485) ~[jetty-servlet-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.Server.handle(Server.java:500) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547) [jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270) [jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) [jetty-io-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388) [jetty-util-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.26.v20200117.jar:9.4.26.v20200117]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: org.gluu.persist.exception.operation.SearchException: Failed to lookup entry
        at org.gluu.persist.couchbase.operation.impl.CouchbaseOperationServiceImpl.lookupImpl(CouchbaseOperationServiceImpl.java:430) ~[oxcore-persistence-couchbase-4.2.1-SNAPSHOT.jar:?]
        at org.gluu.persist.couchbase.operation.impl.CouchbaseOperationServiceImpl.lookup(CouchbaseOperationServiceImpl.java:365) ~[oxcore-persistence-couchbase-4.2.1-SNAPSHOT.jar:?]
        at org.gluu.persist.couchbase.impl.CouchbaseEntryManager.find(CouchbaseEntryManager.java:354) ~[oxcore-persistence-couchbase-4.2.1-SNAPSHOT.jar:?]
```

**Comment by yuriyz** [comment]
It doesn't looks as up to date log. It was fixed here https://github.com/GluuFederation/oxAuth/commit/35c6e888cb8ef4ebeebccd91aa44cf9665413ee1

**Comment by yuriyz** [comment]
OK, I've found typo which leads to it. Fixed here https://github.com/GluuFederation/oxAuth/commit/0de0db1415e314e0467c38cb5e2c6a61aa863aea
