### ISSUE TITLE
Avoid race condition during saving grant object in cache

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1478]
## Describe the issue

Avoid double saving of same grant in cache.
```
2020-10-06 14:42:21,605 ERROR [qtp1989335500-14] [org.gluu.service.cache.NativePersistenceCacheProvider] (NativePersistenceCacheProvider.java:178) - Failed to put entry, key: 7bf1156c-7d3e-4f55-b6c4-ff3c028d06ef, hashedKey: 2e010e3901f595e88bb30d9685d4c7a7dd56fbcadaa5b58376df22c06f699c5c, message: Failed to persist entry: uuid=2e010e3901f595e88bb30d9685d4c7a7dd56fbcadaa5b58376df22c06f699c5c,ou=cache,o=gluu
org.gluu.persist.exception.EntryPersistenceException: Failed to persist entry: uuid=2e010e3901f595e88bb30d9685d4c7a7dd56fbcadaa5b58376df22c06f699c5c,ou=cache,o=gluu
 at org.gluu.persist.ldap.impl.LdapEntryManager.persist(LdapEntryManager.java:192) ~[oxcore-persistence-ldap-4.2.1.Final.jar:?]
...
 at org.gluu.oxauth.model.common.AuthorizationGrant.saveInCache(AuthorizationGrant.java:132) ~[classes/:?]
 at org.gluu.oxauth.model.common.AuthorizationGrant.save(AuthorizationGrant.java:114) ~[classes/:?]
 at org.gluu.oxauth.authorize.ws.rs.AuthorizeRestWebServiceImpl.requestAuthorization(AuthorizeRestWebServiceImpl.java:512) ~[classes/:?]
 at org.gluu.oxauth.authorize.ws.rs.AuthorizeRestWebServiceImpl.requestAuthorizationGet(AuthorizeRestWebServiceImpl.java:151) ~[classes/:?]
 at org.gluu.oxauth.authorize.ws.rs.AuthorizeRestWebServiceImpl$Proxy$_$$_WeldClientProxy.requestAuthorizationGet(Unknown Source) ~[classes/:?]
...
Caused by: org.gluu.persist.exception.operation.DuplicateEntryException: Entry already exists
 at org.gluu.persist.ldap.operation.impl.LdapOperationServiceImpl.addEntryImpl(LdapOperationServiceImpl.java:733) ~[oxcore-persistence-ldap-4.2.1.Final.jar:?]
```

**Comment by yuriyz** [comment]
Done in 4.2.2 and jans.
