### ISSUE TITLE
BUG : NPE during backchannel logout if grant object was not identified

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1505]
## Describe the issue
NPE during backchannel logout if grant object was not identified

```
[gluu.oxauth.session.ws.rs.EndSessionRestWebServiceImpl] (EndSessionRestWebServiceImpl.java:182) - null java.lang.NullPointerException: null at org.gluu.oxauth.session.ws.rs.EndSessionRestWebServiceImpl.backChannel(EndSessionRestWebServiceImpl.java:210) ~[classes/:?] at org.gluu.oxauth.session.ws.rs.EndSessionRestWebServiceImpl.requestEndSession(EndSessionRestWebServiceImpl.java:159) ~[classes/:?] at org.gluu.oxauth.session.ws.rs.EndSessionRestWebServiceImpl$Proxy$_$$_WeldClientProxy.requestEndSession(Unknown Source) ~[classes/:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138) ~[resteasy-jaxrs-3.13.0.Final.jar:3.13.0.Final] at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:543) ~[resteasy-jaxrs-3.13.0.Final.jar:3.13.0.Final] at
```

Support: 9175

**Comment by yuriyz** [comment]
Fixed in 4.2.2 and jans.
