### ISSUE TITLE
Avoid NPE in User Info Endpoint (caused by scope removing)

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1517]
## Describe the issue
Avoid NPE in User Info Endpoint (caused by scope removing)

```
2021-01-07 06:18:27,688 ERROR [qtp2080166188-1064812] [gluu.oxauth.userinfo.ws.rs.UserInfoRestWebServiceImpl] (UserInfoRestWebServiceImpl.java:216) - null
java.lang.NullPointerException: null
    at org.gluu.oxauth.userinfo.ws.rs.UserInfoRestWebServiceImpl.getJSonResponse(UserInfoRestWebServiceImpl.java:339) ~[classes/:?]
    at org.gluu.oxauth.userinfo.ws.rs.UserInfoRestWebServiceImpl.requestUserInfo(UserInfoRestWebServiceImpl.java:209) ~[classes/:?]
    at org.gluu.oxauth.userinfo.ws.rs.UserInfoRestWebServiceImpl.requestUserInfoPost(UserInfoRestWebServiceImpl.java:126) ~[classes/:?]
    at org.gluu.oxauth.userinfo.ws.rs.UserInfoRestWebServiceImpl$Proxy$_$_WeldClientProxy.requestUserInfoPost(Unknown Source) ~[classes/:?]
    at sun.reflect.GeneratedMethodAccessor590.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
```

**Comment by yuriyz** [comment]
Fixed in 4.3 and jans.
