### ISSUE TITLE
Openmetric request fail with label as digits only

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1544]
## Describe the issue
If register month as label, e.g. `202105` prometheus client refuse to consume it.

```
2021-05-28 20:15:24,452 ERROR [qtp634540230-109] [gluu.oxauth.ws.rs.stat.StatWS] (StatWS.java:110) - Invalid metric label name: 202105
java.lang.IllegalArgumentException: Invalid metric label name: 202105
	at io.prometheus.client.Collector.checkMetricLabelName(Collector.java:203) ~[simpleclient-0.9.0.jar:?]
	at io.prometheus.client.SimpleCollector.<init>(SimpleCollector.java:170) ~[simpleclient-0.9.0.jar:?]
	at io.prometheus.client.Counter.<init>(Counter.java:71) ~[simpleclient-0.9.0.jar:?]
	at io.prometheus.client.Counter$Builder.create(Counter.java:77) ~[simpleclient-0.9.0.jar:?]
	at io.prometheus.client.Counter$Builder.create(Counter.java:74) ~[simpleclient-0.9.0.jar:?]
	at io.prometheus.client.SimpleCollector$Builder.register(SimpleCollector.java:245) ~[simpleclient-0.9.0.jar:?]
	at org.gluu.oxauth.ws.rs.stat.StatWS.createOpenMetricsResponse(StatWS.java:243) ~[classes/:?]
	at org.gluu.oxauth.ws.rs.stat.StatWS.stat(StatWS.java:99) ~[classes/:?]
	at org.gluu.oxauth.ws.rs.stat.StatWS.statGet(StatWS.java:71) ~[classes/:?]
	at org.gluu.oxauth.ws.rs.stat.StatWS$Proxy$_$$_WeldClientProxy.statGet(Unknown Source) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.j
```

**Comment by yuriyz** [comment]
Fixed in 4.3 and jans.
