### ISSUE TITLE
Fix: exception during openmetrics response construction from stat endpoint (MAU)

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1553]
## Describe the issue

Exception during openmetrics response construction from stat endpoint (MAU)
```
2021-07-19 10:12:18,865 ERROR [qtp222511810-604] [gluu.oxauth.ws.rs.stat.StatWS] (StatWS.java:109) - Collector already registered that provides name: access_token
java.lang.IllegalArgumentException: Collector already registered that provides name: access_token
	at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:54) ~[simpleclient-0.9.0.jar:?]
	at io.prometheus.client.SimpleCollector$Builder.register(SimpleCollector.java:246) ~[simpleclient-0.9.0.jar:?]
	at org.gluu.oxauth.ws.rs.stat.StatWS.createOpenMetricsResponse(StatWS.java:255) ~[classes/:?]
	at org.gluu.oxauth.ws.rs.stat.StatWS.stat(StatWS.java:98) ~[classes/:?]
	at org.gluu.oxauth.ws.rs.stat.StatWS.statGet(StatWS.java:70) ~[classes/:?]
	at org.gluu.oxauth.ws.rs.stat.StatWS$Proxy$_$$_WeldClientProxy.statGet(Unknown Source) ~[classes/:?]
	at jdk.internal.reflect.GeneratedMethodAccessor537.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
```

**Comment by yuriyz** [comment]
Fixed in 4.3 and jans. Tested by @MohitMaliFtechiz
