### ISSUE TITLE
Aggregation request to stat endpoint should not fail if data for some node got corrupted

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1555]
## Describe the issue
During aggregation we may run on node which data got corrupted. We should not fail entire request. Instead log entry and data that got corrupted with error log level and continue processing.

```
2021-07-23 14:47:28,027 ERROR [qtp534906248-19] [as.server.ws.rs.stat.StatWS] (StatWS.java:154) - Illegal base64 character 11
java.lang.IllegalArgumentException: Illegal base64 character 11
at java.util.Base64$Decoder.decode0(Base64.java:743) ~[?:?]
at java.util.Base64$Decoder.decode(Base64.java:535) ~[?:?]
at java.util.Base64$Decoder.decode(Base64.java:558) ~[?:?]
at io.jans.as.server.ws.rs.stat.StatWS.userCardinality(StatWS.java:187) ~[classes/:?]
```

**Comment by yuriyz** [comment]
Fixed in 4.3 and jans.
