### ISSUE TITLE
enhancement: Do not print stacktraces when we expect object to not be found.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1646]
## Describe the issue

If session is expired and try to fetch it, it prints verbose stack trace which produce a lot of noise in logs. We have to log such event without stacktrace.

```
    at org.gluu.oxauth.service.SessionIdService.getSessionId(SessionIdService.java:820)
    at org.gluu.oxauth.service.SessionIdService.getSessionId(SessionIdService.java:811)
    at org.gluu.oxauth.service.SessionIdService$Proxy$_$_WeldClientProxy.getSessionId(Unknown Source)
    at org.gluu.oxauth.auth.AuthenticationFilter.doFilter(AuthenticationFilter.java:199)
```

Places to check:

- https://github.com/GluuFederation/oxAuth/blob/9523eb2ed86d46d69cb39d3c79262444d0ab3157/Server/src/main/java/org/gluu/oxauth/auth/Authenticator.java#L698
- https://github.com/GluuFederation/oxAuth/blob/9523eb2ed86d46d69cb39d3c79262444d0ab3157/Server/src/main/java/org/gluu/oxauth/auth/AuthenticationFilter.java#L199
- https://github.com/GluuFederation/oxAuth/blob/9523eb2ed86d46d69cb39d3c79262444d0ab3157/Server/src/main/java/org/gluu/oxauth/authorize/ws/rs/AuthorizeRestWebServiceImpl.java#L912

For reference
https://github.com/GluuFederation/oxAuth/commit/e48902bac59f3769d3f58f87429e7400e857bbb0

**Comment by yuriyz** [comment]
Done in both oxauth (main) and jans.
