### ISSUE TITLE
Server startup error after updating code wich contain jwks fixes

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#165]
Old 2.4.1 installations stop working after updating to latest coded which contains fix:
"Update test jwks data to conform latest code"

<code>
2016-02-18 14:17:19,674 INFO  [org.xdi.oxauth.model.util.JwtUtil] Adding Bouncy Castle Provider
2016-02-18 14:17:19,967 INFO  [org.xdi.oxauth.model.config.ConfigurationFactory] Loading configuration from LDAP...
2016-02-18 14:17:20,546 ERROR [org.xdi.oxauth.model.config.ConfigurationFactory] Unrecognized field "keyType" (Class org.xdi.oxauth.model.jwk.JSONWebKey), not marked as ignorable  at [Source: java.io.StringReader@5eff20a0; line: 3, column: 21] (through reference chain: org.xdi.oxauth.model.jwk.JSONWebKeySet["keys"]->org.xdi.oxauth.model.jwk.JSONWebKey["keyType"])
org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "keyType" (Class org.xdi.oxauth.model.jwk.JSONWebKey), not marked as ignorable  at [Source: java.io.StringReader@5eff20a0; line: 3, column: 21] (through reference chain: org.xdi.oxauth.model.jwk.JSONWebKeySet["keys"]->org.xdi.oxauth.model.jwk.JSONWebKey["keyType"])
	at org.codehaus.jackson.map.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:53)

...
	at org.xdi.oxauth.model.config.ConfigurationFactory.initWebKeysFromJson(ConfigurationFactory.java:320)
</code>

**Comment by yurem** [comment]
There 2 approaches for migration to 2.4.2:
1) Full reinstall
2) Try to load data from old format
3) catch this exception, regenerate keys and persist to LDAP

I vote for approach 3. It will help us with future jwks updates too. But if it's easy to implement (no major changes in format) we can use seond approach.

**Comment by nynymike** [comment]
Let's proceed with #3, and we can figure out in the next release if there is a better way to deal with this.

**Comment by yurem** [comment]
Fixed
