### ISSUE TITLE
bug(oxauth): fix NPE in JwtAuthorizationRequest

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1723]
## Describe the issue
```
java.lang.NullPointerException: null
        at org.gluu.oxauth.model.authorize.JwtAuthorizationRequest.createJwtRequest(JwtAuthorizationRequest.java:466) ~[classes/:?]
        at org.gluu.oxauth.bcauthorize.ws.rs.BackchannelAuthorizeRestWebServiceImpl.requestBackchannelAuthorizationPost(BackchannelAuthorizeRestWebServiceImpl.java:167) ~[classes/:?]
        at org.gluu.oxauth.bcauthorize.ws.rs.BackchannelAuthorizeRestWebServiceImpl$Proxy$_$$_WeldClientProxy.requestBackchannelAuthorizationPost(Unknown Source) ~[classes/:?]
        at jdk.internal.reflect.GeneratedMethodAccessor660.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
```

## Expected behavior
There must not be NPE.

## Actual behavior
NPE if redirect response is null.

**Comment by yuriyz** [comment]
Fixed in https://github.com/GluuFederation/oxAuth/pull/1724
