### ISSUE TITLE
test(oxauth): SpontaneousScopeHttpTest fails during build

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1725]
## Describe the issue

```
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at org.gluu.oxauth.ws.rs.SpontaneousScopeHttpTest.spontaneousScope(SpontaneousScopeHttpTest.java:54)
```

## Steps To Reproduce
Run build with tests

## Expected behavior
Test must pass.

## Actual behavior
Fails.

**Comment by yuriyz** [comment]
Fixed in https://github.com/GluuFederation/oxAuth/pull/1726
