### ISSUE TITLE
fix(oxauth): do not log WebApplicationException as error since it's expected behavior

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1747]
## Describe the issue

The following ERROR message appears very often in our logs. But we cannot gather any useful information from it. At least the redirect uri and client id should be logged. And is it really an error?

```
HTTP 400 Bad Request javax.ws.rs.WebApplicationException: HTTP 400 Bad Request at org.gluu.oxauth.authorize.ws.rs.AuthorizeRestWebServiceValidator.validateRedirectUri(AuthorizeRestWebServiceValidator.java:268) ~[classes/:?] at org.gluu.oxauth.authorize.ws.rs.AuthorizeRestWebServiceImpl.requestAuthorization(AuthorizeRestWebServiceImpl.java:231) ~[classes/:?] at org.gluu.oxauth.authorize.ws.rs.AuthorizeRestWebServiceImpl.requestAuthorizationGet(AuthorizeRestWebServiceImpl.java:161) ~[classes/:?] at org.gluu.oxauth.authorize.ws.rs.AuthorizeRestWebServiceImpl$Proxy$_$$_WeldClientProxy.requestAuthorizationGet(Unknown Source) ~[classes/:?] at jdk.internal.reflect.GeneratedMethodAccessor372.invoke(Unknown Source) ~[?:?] at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170) ~[resteasy-core-4.7.5.Final.jar:4.7.5.Final] at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130) ~[resteasy-core-4.7.5.Final.jar:4.7.5.Final] at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660) ~[resteasy-core-4.7.5.Final.jar:4.7.5.Final] at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524) ~[resteasy-core-4.7.5.Final.jar:4.7.5.Final] at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474) ~[resteasy-core-4.7.5.Final.jar:4.7.5.Final] at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364) ~[resteasy-core-4.7.5.Final.jar:4.7.5.Final] at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476) ~[resteasy-core-4.7.5.Final.jar:4.7.5.Final] at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434) ~[resteasy-core-4.7.5.Final.jar:4.7.5.Final] at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408) ~[resteasy-core-4.7.5.Final.jar:4.7.5.Final] at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69) ~[resteasy-core-4.7.5.Final.jar:4.7.5.Final] at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492) ~[resteasy-core-4.7.5.Final.jar:4.7.5.Final] at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261) ~[resteasy-core-4.7.5.Final.jar:4.7.5.Final] at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161) ~[resteasy-core-4.7.5.Final.jar:4.7.5.Final] at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364) ~[resteasy-core-4.7.5.Final.jar:4.7.5.Final] at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164) ~[resteasy-core-4.7.5.Final.jar:4.7.5.Final] at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247) ~[resteasy-core-4.7.5.Final.jar:4.7.5.Final]
```

## Expected behavior
Log in TRACE
## Actual behavior
Logged in ERROR

Support: 10975

**Comment by yuriyz** [comment]
Fixed in https://github.com/GluuFederation/oxAuth/pull/1758
