### ISSUE TITLE
UMA 1.0.1 : ticket invalidation

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#181]
2016-03-10 15:35:53,720 ERROR [org.gluu.site.ldap.OperationsFacade] Entry can't be modified
LDAPException(resultCode=67 (not allowed on RDN), errorMessage='Entry oxTicket=393df6bf-8ab5-49f4-a728-e25796a56850,ou=uma_resource_set_permission,inum=@!0E32.1CE6.78E1.1E46!0001!5D86.60DC!0008!1A4E.1FEE,ou=clients,o=@!0E32.1CE6.78E1.1E46!0001!5D86.60DC,o=gluu cannot be modified because the change to attribute oxTicket would have removed a value used in the RDN', diagnosticMessage='Entry oxTicket=393df6bf-8ab5-49f4-a728-e25796a56850,ou=uma_resource_set_permission,inum=@!0E32.1CE6.78E1.1E46!0001!5D86.60DC!0008!1A4E.1FEE,ou=clients,o=@!0E32.1CE6.78E1.1E46!0001!5D86.60DC,o=gluu cannot be modified because the change to attribute oxTicket would have removed a value used in the RDN')
        at com.unboundid.ldap.sdk.LDAPConnection.modify(LDAPConnection.java:2384)
        at com.unboundid.ldap.sdk.AbstractConnectionPool.modify(AbstractConnectionPool.java:1287)
        at org.gluu.site.ldap.OperationsFacade.modifyEntry(OperationsFacade.java:387)
        at org.gluu.site.ldap.OperationsFacade.updateEntry(OperationsFacade.java:374)
        at org.gluu.site.ldap.persistence.LdapEntryManager.merge(LdapEntryManager.java:191)
        at org.gluu.site.ldap.persistence.AbstractEntryManager.merge(AbstractEntryManager.java:278)
        at org.gluu.site.ldap.persistence.AbstractEntryManager.merge(AbstractEntryManager.java:293)
        at org.xdi.oxauth.uma.ws.rs.RptPermissionAuthorizationWS.invalidateTicket(RptPermissionAuthorizationWS.java:168)
        at org.xdi.oxauth.uma.ws.rs.RptPermissionAuthorizationWS.authorizeRptPermission(RptPermissionAuthorizationWS.java:156)
        at org.xdi.oxauth.uma.ws.rs.RptPermissionAuthorizationWS.requestRptPermissionAuthorization(RptPermissionAuthorizationWS.java:87)

**Comment by yuriyz** [comment]
Fixed in https://github.com/GluuFederation/oxAuth/commit/b89ef83e90577eb3b89aa32628fcc54dac81b134
