### ISSUE TITLE
Unnecessary "session not found" error messages during refresh token flow

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#1824]
## Description
As it was first reported in Support Board ticket 11218, and acknowledged by @yuriyz in the ticket, oxAuth may log "session not found" kind of errors excessively in certain cases. In particular, quoting the user:
>when ID token is getting created, at that time oxauth is trying to find the session associated with the authorization grant. Since, this is refresh token, there are very less chances of being able to find the SessionId associated

## Steps to reproduce
1. Acquire a refresh token using any suitable OIDC flow
2. Wait until related oxAuth session has timed out, or terminate it with a call to `/end_session` endpoint
3. Call `/token` endpoint with refresh token to issue a new access token while tailing `oxuath.log`

## Expected behavior
The check for existing session is possibly not needed in this case, reducing log's cluttering with high-severity error messages not related to an actual issue

## Actual behavior

And error like below is logged:
```
(SessionIdService.java:793) - Failed to get session by dn: oxId=ca2a0a20-bef5-468f-9708-759ce02919ff,ou=sessions,o=gluu
org.gluu.persist.exception.EntryPersistenceException: Failed to find entry: oxId=ca2a0a20-bef5-468f-9708-759ce02919ff,ou=sessions,o=gluu
        at org.gluu.orm.couchbase.impl.CouchbaseEntryManager.find(CouchbaseEntryManager.java:376) ~[gluu-orm-couchbase-4.4.1.Final.jar:?]
        at org.gluu.persist.impl.BaseEntryManager.find(BaseEntryManager.java:714) ~[gluu-orm-core-4.4.1.Final.jar:?]
        at org.gluu.persist.impl.BaseEntryManager.find(BaseEntryManager.java:593) ~[gluu-orm-core-4.4.1.Final.jar:?]
        at org.gluu.persist.impl.BaseEntryManager.find(BaseEntryManager.java:580) ~[gluu-orm-core-4.4.1.Final.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
        at org.gluu.persist.PersistenceEntryManager$EntityManager$1948487569$Proxy$_$$_WeldClientProxy.find(Unknown Source) ~[gluu-orm-core-4.4.1.Final.jar:?]
        at org.gluu.oxauth.service.SessionIdService.getSessionByDn(SessionIdService.java:787) ~[classes/:?]
        at org.gluu.oxauth.service.SessionIdService.getSessionByDn(SessionIdService.java:751) ~[classes/:?]
        at org.gluu.oxauth.service.SessionIdService$Proxy$_$$_WeldClientProxy.getSessionByDn(Unknown Source) ~[classes/:?]
        at org.gluu.oxauth.model.token.IdTokenFactory.fillClaims(IdTokenFactory.java:126) ~[classes/:?]
        at org.gluu.oxauth.model.token.IdTokenFactory.createJwr(IdTokenFactory.java:270) ~[classes/:?]
        at org.gluu.oxauth.model.token.IdTokenFactory$Proxy$_$$_WeldClientProxy.createJwr(Unknown Source) ~[classes/:?]
        at org.gluu.oxauth.model.common.AuthorizationGrant.createIdToken(AuthorizationGrant.java:102) ~[classes/:?]
        at org.gluu.oxauth.model.common.AuthorizationGrant.createIdToken(AuthorizationGrant.java:309) ~[classes/:?]
        at org.gluu.oxauth.token.ws.rs.TokenRestWebServiceImpl.requestAccessToken(TokenRestWebServiceImpl.java:291) ~[classes/:?]
        at org.gluu.oxauth.token.ws.rs.TokenRestWebServiceImpl$Proxy$_$$_WeldClientProxy.requestAccessToken(Unknown Source) ~[classes/:?]
        at jdk.internal.reflect.GeneratedMethodAccessor270.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170) ~[resteasy-core-4.7.5.Final.jar:4.7.5.Final]
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130) ~[resteasy-core-4.7.5.Final.jar:4.7.5.Final]
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660) ~[resteasy-core-4.7.5.Final.jar:4.7.5.Final]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524) ~[resteasy-core-4.7.5.Final.jar:4.7.5.Final]
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474) ~[resteasy-core-4.7.5.Final.jar:4.7.5.Final]
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364) ~[resteasy-core-4.7.5.Final.jar:4.7.5.Final]
```

**Comment by yuriyz** [comment]
Fixed in master and 4.5.1
