### ISSUE TITLE
fix(oxauth): Modify AT in Update token script has errors

### ISSUE THREAD

**Issue by maduvena** [GluuFederation/oxAuth#1833]
oxauth.war - 4.5.1 version.

Script:
```
   def modifyAccessToken(self, accessToken, context):
        print "Update token script. before --- Modify access token: %s" % accessToken
        profiles = Sets.newHashSet( "openid", "profile","user_name")
        
        # point 1
        context.overwriteAccessTokenScopes(accessToken, profiles)
        
        #point 2     
        accessToken.getClaims().setClaim("claim_name", "claimValue")
        print "Update token script. Modify access token: %s" % accessToken
        return True
```

1. Scope not getting updated
2. claims are not updated 
```
2023-05-16 07:52:22,317 INFO  [qtp966739377-17] [org.gluu.service.cache.NativePersistenceCacheProvider] (NativePersistenceCacheProvider.java:79) - Created NATIVE_PERSISTENCE cache provider. `baseDn`: ou=cache,o=gluu
2023-05-16 07:52:23,929 ERROR [qtp966739377-17] [org.gluu.oxauth.service.external.ExternalUpdateTokenService] (ExternalUpdateTokenService.java:145) - AttributeError: 'org.gluu.oxauth.model.common.AccessToken' object has no attribute 'getClaims'
org.python.core.PyException: AttributeError: 'org.gluu.oxauth.model.common.AccessToken' object has no attribute 'getClaims'
        at org.python.core.Py.AttributeError(Py.java:176) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
        at org.python.core.PyObject.noAttributeError(PyObject.java:965) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
        at org.python.core.PyObject.object___getattribute__(PyObject.java:3752) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
        at org.python.core.PyObject$object___getattribute___exposer.__call__(Unknown Source) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
        at org.python.core.Deriveds.__findattr_ex__(Deriveds.java:59) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
        at org.python.core.PyObjectDerived.__findattr_ex__(PyObjectDerived.java:1036) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
        at org.python.core.PyObject.__getattr__(PyObject.java:957) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
        at org.python.pycode._pyx1.modifyAccessToken$8(update_token_sample.py:57) ~[?:?]
        at org.python.pycode._pyx1.call_function(update_token_sample.py) ~[?:?]
        at org.python.core.PyTableCode.call(PyTableCode.java:173) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
        at org.python.core.PyBaseCode.call(PyBaseCode.java:306) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
        at org.python.core.PyBaseCode.call(PyBaseCode.java:197) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
        at org.python.core.PyFunction.__call__(PyFunction.java:485) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
        at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
        at org.python.core.PyMethod.__call__(PyMethod.java:228) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
        at org.python.core.PyMethod.__call__(PyMethod.java:218) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
        at org.python.core.PyMethod.__call__(PyMethod.java:213) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
        at org.python.core.PyObject._jcallexc(PyObject.java:3565) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
        at org.python.core.PyObject._jcall(PyObject.java:3598) ~[jython-standalone-2.7.3.jar:2.7.3b1-SNAPSHOT]
        at org.python.proxies.__main__$UpdateToken$1.modifyAccessToken(Unknown Source) ~[?:?]
        at org.gluu.oxauth.service.external.ExternalUpdateTokenService.modifyAccessToken(ExternalUpdateTokenService.java:137) ~[classes/:?]
        at org.gluu.oxauth.service.external.ExternalUpdateTokenService.modifyAccessToken(ExternalUpdateTokenService.java:160) ~[classes/:?]
        at org.gluu.oxauth.service.external.ExternalUpdateTokenService$Proxy$_$$_WeldClientProxy.modifyAccessToken(Unknown Source) ~[classes/:?]
        at org.gluu.oxauth.model.common.AuthorizationGrant.createAccessToken(AuthorizationGrant.java:202) ~[classes/:?]
        
        ```

**Comment by yurem** [comment]
By default oxAuth creates access token with type `BEARER`, plain token. In your example you are trying to get JWT token claims, In order to allow to do this client should has `accessTokenAsJwt = true`

**Comment by yurem** [comment]
Can you try to use:
```
accessToken.getJwt().getClaims().setClaim("claim_name", "claimValue")
```
accessToken when `accessTokenAsJwt = true` has type [JwtSigner](accessToken.getJwt().getClaims().setClaim("claim_name", "claimValue")).

**Comment by yurem** [comment]
Fix: https://github.com/GluuFederation/oxAuth/commit/f14b4b920d9c4ca0f18664ddd06f46d36fbb9b82

**Comment by yurem** [comment]
With this fix you can use next line:
```
context.getClaims().setClaim("claim_name", "claimValue")
```
