### ISSUE TITLE
UMA authentication: "JWT authentication failed: Cannot verify the JWT"

### ISSUE THREAD

**Issue by uboznikov** [GluuFederation/oxAuth#224]
Encountered in oxScimClient Jenkins build and encountered also in local. Local stacktrace follows:

`DEBUG [org.xdi.oxauth.service.ClientService] Found 1 entries for client id = @!D58A.A2C6.9B5E.11DA!0001!C69B.EF8E!0008!0E9E.8E41
DEBUG [org.xdi.oxauth.model.util.JwtUtil] Retrieving JWK Key...
INFO  [org.xdi.oxauth.auth.AuthenticationFilter] JWT authentication failed: Cannot verify the JWT
org.xdi.oxauth.model.exception.InvalidJwtException: Cannot verify the JWT
        at org.xdi.oxauth.model.token.ClientAssertion.<init>(ClientAssertion.java:48)
        at org.xdi.oxauth.auth.AuthenticationFilter.processJwtAuth(AuthenticationFilter.java:324)
        at org.xdi.oxauth.auth.AuthenticationFilter.access$100(AuthenticationFilter.java:62)
        at org.xdi.oxauth.auth.AuthenticationFilter$1.process(AuthenticationFilter.java:85)
        at org.jboss.seam.servlet.ContextualHttpServletRequest.run(ContextualHttpServletRequest.java:65)
        at org.xdi.oxauth.auth.AuthenticationFilter.doFilter(AuthenticationFilter.java:128)
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
        at org.jboss.seam.web.IdentityFilter.doFilter(IdentityFilter.java:40)
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
        at org.jboss.seam.web.MultipartFilter.doFilter(MultipartFilter.java:90)
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
        at org.jboss.seam.web.ExceptionFilter.doFilter(ExceptionFilter.java:64)
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
        at org.jboss.seam.web.RedirectFilter.doFilter(RedirectFilter.java:45)
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
        at org.jboss.seam.servlet.SeamFilter.doFilter(SeamFilter.java:158)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
        at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:190)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
DEBUG [org.xdi.oxauth.model.error.ErrorResponseFactory] Looking for the error with id: invalid_client
DEBUG [org.xdi.oxauth.model.error.ErrorResponseFactory] Found error, id: invalid_client
`

**Comment by yurem** [comment]
Resolved
