### ISSUE TITLE
oxauth-rp is war file is corrupt / broken

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#253]
oxauth-rp is not starting

```
INFO   | jvm 1    | 2016/07/12 15:31:36 | org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/oxauth-rp]]
INFO   | jvm 1    | 2016/07/12 15:31:36 |       at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
INFO   | jvm 1    | 2016/07/12 15:31:36 |       at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
INFO   | jvm 1    | 2016/07/12 15:31:36 |       at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
INFO   | jvm 1    | 2016/07/12 15:31:36 |       at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
INFO   | jvm 1    | 2016/07/12 15:31:36 |       at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1095)
INFO   | jvm 1    | 2016/07/12 15:31:36 |       at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1960)
INFO   | jvm 1    | 2016/07/12 15:31:36 |       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
INFO   | jvm 1    | 2016/07/12 15:31:36 |       at java.util.concurrent.FutureTask.run(FutureTask.java:262)
INFO   | jvm 1    | 2016/07/12 15:31:36 |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/07/12 15:31:36 |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/07/12 15:31:36 |       at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/07/12 15:31:36 | Caused by: org.apache.catalina.LifecycleException: Error in resourceStart()
INFO   | jvm 1    | 2016/07/12 15:31:36 |       at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5320)
INFO   | jvm 1    | 2016/07/12 15:31:36 |       at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
INFO   | jvm 1    | 2016/07/12 15:31:36 |       ... 10 more
INFO   | jvm 1    | 2016/07/12 15:31:36 |
INFO   | jvm 1    | 2016/07/12 15:31:36 | Jul 12, 2016 3:31:36 PM org.apache.catalina.startup.HostConfig deployWAR
INFO   | jvm 1    | 2016/07/12 15:31:36 | SEVERE: Error deploying web application archive /opt/apache-tomcat-7.0.65/webapps/oxauth-rp.war
INFO   | jvm 1    | 2016/07/12 15:31:36 | java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/oxauth-rp]]
INFO   | jvm 1    | 2016/07/12 15:31:36 |       at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:905)

```

**Comment by qbert2k** [comment]
I cannot reproduce the problem.
I have tried in my local env and in ce-dev2.gluu.org, both are working fine.
