### ISSUE TITLE
oxauth-client can't sign token request using JKS generated by KeyGenerator

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#254]
On some server there is strange situation:
Valentino Pecaoco>> I'm getting this error:
Valentino Pecaoco>> ERROR [org.xdi.oxauth.client.TokenRequest] Could not sign data
java.security.SignatureException: Could not sign data
        at sun.security.ec.ECDSASignature.engineSign(ECDSASignature.java:297)
        at java.security.Signature$Delegate.engineSign(Signature.java:1205)
        at java.security.Signature.sign(Signature.java:578)
        at org.xdi.oxauth.model.crypto.OxAuthCryptoProvider.sign(OxAuthCryptoProvider.java:212)
        at org.xdi.oxauth.client.TokenRequest.getClientAssertion(TokenRequest.java:357)
        at org.xdi.oxauth.client.TokenClient.exec(TokenClient.java:295)
        at org.xdi.oxauth.client.uma.wrapper.UmaClient.request(UmaClient.java:173)
        at org.gluu.oxtrust.service.UmaProtectionService.retrievePatToken(UmaProtectionService.java:290)
        at org.gluu.oxtrust.service.UmaProtectionService.getPatToken(UmaProtectionService.java:116)
        at org.gluu.oxtrust.service.UmaProtectionService.isExistPatToken(UmaProtectionService.java:131)
        at org.gluu.oxtrust.service.UmaProtectionService.isEnabledUmaAuthentication(UmaProtectionService.java:126)

**Comment by yurem** [comment]
Fixed
