### ISSUE TITLE
KeyGenerator should not uses server log files

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#28]
In CE we get next error in installation log:
6:42:01 04/02/15 Runnning: /bin/su tomcat -c /usr/java/latest/bin/java -cp /home/tomcat/lib/bcprov-jdk16-1.46.jar:/home/tomcat/lib/commons-lang-2.6.jar:/home/tomcat/lib/log4j-1.2.14.jar:/home/tomcat/lib/commons-codec-1.5.jar:/home/tomcat/lib/jettison-1.3.jar:/home/tomcat/lib/oxauth-model.jar:/home/tomcat/lib/oxauth.jar org.xdi.oxauth.util.KeyGenerator
16:42:05 04/02/15 log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /logs/oxauth_persistence_ldap_statistics.log (No such file or directory)
at java.io.FileOutputStream.open(Native Method)
at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
at java.io.FileOutputStream.<init>(FileOutputStream.java:142)
at org.apache.log4j.FileAppender.setFile(FileAppender.java:289)
at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:163)
at org.apache.log4j.DailyRollingFileAppender.activateOptions(DailyRollingFileAppender.java:215)
at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:256)
at org.apache.log4j.xml.DOMConfigurator.parseAppender(DOMConfigurator.java:220)
at org.apache.log4j.xml.DOMConfigurator.findAppenderByName(DOMConfigurator.java:150)
at org.apache.log4j.xml.DOMConfigurator.findAppenderByReference(DOMConfigurator.java:163)
at org.apache.log4j.xml.DOMConfigurator.parseChildrenOfLoggerElement(DOMConfigurator.java:425)
at org.apache.log4j.xml.DOMConfigurator.parseCategory(DOMConfigurator.java:345)
at org.apache.log4j.xml.DOMConfigurator.parse(DOMConfigurator.java:827)
at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:712)
at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:618)
at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:470)
at org.apache.log4j.LogManager.<clinit>(LogManager.java:122)
at org.apache.log4j.Logger.getLogger(Logger.java:117)
at org.xdi.oxauth.model.util.JwtUtil.<clinit>(JwtUtil.java:84)
at org.xdi.oxauth.model.crypto.signature.RSAPrivateKey.toJSONObject(RSAPrivateKey.java:57)
at org.xdi.oxauth.model.crypto.Key.toJSONObject(Key.java:112)
at org.xdi.oxauth.util.KeyGenerator.generateRS256Keys(KeyGenerator.java:66)
at org.xdi.oxauth.util.KeyGenerator.main(KeyGenerator.java:31)
log4j:ERROR Either File or DatePattern options are not set for appender [OX_PERSISTENCE_LDAP_STATISTICS_FILE].
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /logs/oxauth.log (No such file or directory)
at java.io.FileOutputStream.open(Native Method)
at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
at java.io.FileOutputStream.<init>(FileOutputStream.java:142)
at org.apache.log4j.FileAppender.setFile(FileAppender.java:289)
at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:163)
at org.apache.log4j.DailyRollingFileAppender.activateOptions(DailyRollingFileAppender.java:215)
at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:256)
at org.apache.log4j.xml.DOMConfigurator.parseAppender(DOMConfigurator.java:220)
at org.apache.log4j.xml.DOMConfigurator.findAppenderByName(DOMConfigurator.java:150)
at org.apache.log4j.xml.DOMConfigurator.findAppenderByReference(DOMConfigurator.java:163)
at org.apache.log4j.xml.DOMConfigurator.parseChildrenOfLoggerElement(DOMConfigurator.java:425)
at org.apache.log4j.xml.DOMConfigurator.parseRoot(DOMConfigurator.java:394)
at org.apache.log4j.xml.DOMConfigurator.parse(DOMConfigurator.java:829)
at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:712)
at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:618)
at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:470)
at org.apache.log4j.LogManager.<clinit>(LogManager.java:122)
at org.apache.log4j.Logger.getLogger(Logger.java:117)
at org.xdi.oxauth.model.util.JwtUtil.<clinit>(JwtUtil.java:84)
at org.xdi.oxauth.model.crypto.signature.RSAPrivateKey.toJSONObject(RSAPrivateKey.java:57)
at org.xdi.oxauth.model.crypto.Key.toJSONObject(Key.java:112)
at org.xdi.oxauth.util.KeyGenerator.generateRS256Keys(KeyGenerator.java:66)
at org.xdi.oxauth.util.KeyGenerator.main(KeyGenerator.java:31)
log4j:ERROR Either File or DatePattern options are not set for appender [FILE].

**Comment by yurem** [comment]
https://support.gluu.org/view/installation/setuppy-throwing-error-running-keygenerator-java-program/1767
