### ISSUE TITLE
On acr changed authorization request oxauth returns not clear 500 error - we need redirect back to client to pass control back to client

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#290]
https://ce-dev2.gluu.org/oxauth/seam/resource/restv1/oxauth/authorize?response_type=code&client_id=@!40EA.D454.9D4F.E876!0001!ECE8.BBEF!0008!2D14.B75A&client_secret=8af95600-ca47-439d-a30f-1d4ca5aec2ce&redirect_uri=https://gluu.loc/wp-login.php?option=oxdOpenId&scope=openid+profile+email+address+clientinfo+mobile_phone+phone&state=af0ifjsldkj&nonce=n-0S6_WzA2Mj&acr_values=basic

2016-08-24 13:25:22,895 ERROR [xdi.oxauth.authorize.ws.rs.AuthorizeRestWebServiceImpl]
org.xdi.oxauth.service.AcrChangedException
        at org.xdi.oxauth.service.SessionStateService.assertAuthenticatedSessionCorrespondsToNewRequest(SessionStateServ
ice.java:83)
        at sun.reflect.GeneratedMethodAccessor676.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
        at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32)
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56)
        at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28)
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
        at org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:79)
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
        at org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44)
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
        at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107)
        at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:196)
        at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:114)
        at org.xdi.oxauth.service.SessionStateService_$$_javassist_seam_29.assertAuthenticatedSessionCorrespondsToNewReq
uest(SessionStateService_$$_javassist_seam_29.java)
        at org.xdi.oxauth.authorize.ws.rs.AuthorizeRestWebServiceImpl.requestAuthorization(AuthorizeRestWebServiceImpl.j
ava:165)
        at org.xdi.oxauth.authorize.ws.rs.AuthorizeRestWebServiceImpl.requestAuthorizationGet(AuthorizeRestWebServiceImp
l.java:105)
        at sun.reflect.GeneratedMethodAccessor801.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by yuriyz** [comment]
added both : clear logs that prompt=login needs to be added in order to alter existing session and also redirect back to RP with clear error message and hint.
