### ISSUE TITLE
Faled to log in in cluter

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#360]
```
 2016-10-26 17:34:39,184 INFO  [org.xdi.oxauth.auth.Authenticator] Authentication success for Client: '@XYZ'
 2016-10-26 17:40:28,441 ERROR [org.jboss.seam.exception.Exceptions] handled and logged exception
 javax.servlet.ServletException: viewId:/login.htm - View /login.htm could not be restored.
         at javax.faces.webapp.FacesServlet.service(FacesServlet.java:606)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
         at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
         at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)
         at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:411)
         at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
         at org.jboss.seam.web.RewriteFilter.process(RewriteFilter.java:98)
         at org.jboss.seam.web.RewriteFilter.doFilter(RewriteFilter.java:57)
         at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
         at org.jboss.seam.web.LoggingFilter.doFilter(LoggingFilter.java:60)
         at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
         at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73)
         at org.jboss.seam.web.IdentityFilter.doFilter(IdentityFilter.java:40)
         at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
         at org.jboss.seam.web.MultipartFilter.doFilter(MultipartFilter.java:90)
         at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
         at org.jboss.seam.web.ExceptionFilter.doFilter(ExceptionFilter.java:64)
         at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
         at org.jboss.seam.web.RedirectFilter.doFilter(RedirectFilter.java:45)
         at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
         at org.jboss.seam.servlet.SeamFilter.doFilter(SeamFilter.java:158)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
         at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:190)
         at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
         at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
         at java.lang.Thread.run(Thread.java:745)
 Caused by: javax.faces.application.ViewExpiredException: viewId:/login.htm - View /login.htm could not be restored.
         at com.sun.faces.lifecycle.RestoreViewPhase.execute(RestoreViewPhase.java:205)
         at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
         at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:116)
         at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118)
         at javax.faces.webapp.FacesServlet.service(FacesServlet.java:593)
```

**Comment by mzico** [comment]
@yurem : there is one github issue on this already. [Here](https://github.com/GluuFederation/oxAuth/issues/355) it is.

**Comment by yurem** [comment]
Fixed, @mzico Can you test?

**Comment by mzico** [comment]
@yurem : latest oxAuth war?

**Comment by mzico** [comment]
@yurem : I tried oxauth.war from http://ox.gluu.org/maven/org/xdi/oxauth-server/2.4.4.sp2_openldap/

Seems like loop is still there. 

Here is what I can oxauth.log: 

```
2016-11-08 14:58:03,163 INFO  [net.sf.ehcache.util.UpdateChecker] New update(s) found: 2.4.7 [http://www.terracotta.org/confluence/display/release/Release+Notes+Ehcache+Core+2.4]. Please check http://ehcache.org for the latest version.
2016-11-08 14:58:07,188 INFO  [org.xdi.oxauth.service.AuthenticationService] Attempting to redirect user: SessionUser: SessionState, dn='uniqueIdentifier=f606e0a1-b6ee-4105-a8ed-b1ca87669413,ou=session,o=@!1D99.75E3.7043.4235!0001!757D.DC21,o=gluu', id='f606e0a1-b6ee-4105-a8ed-b1ca87669413', isJwt=false, lastUsedAt=Tue Nov 08 14:58:07 UTC 2016, userDn='inum=@!1D99.75E3.7043.4235!0001!757D.DC21!0000!A8F2.DE1E.D7FB,ou=people,o=@!1D99.75E3.7043.4235!0001!757D.DC21,o=gluu', authenticationTime=Tue Nov 08 14:58:07 UTC 2016, state=authenticated, permissionGranted=null, permissionGrantedMap=null, sessionAttributes={auth_step=1, acr=internal, remote_ip=27.147.201.5, scope=openid profile email user_name, response_type=code id_token, redirect_uri=https://clustertest.gluu.org/identity/authentication/authcode, nonce=nonce, client_id=@!1D99.75E3.7043.4235!0001!757D.DC21!0008!E36B.A61A, auth_user=admin}, persisted=true}
2016-11-08 14:58:07,190 INFO  [org.xdi.oxauth.service.AuthenticationService] Attempting to redirect user: User: org.xdi.oxauth.model.common.User@1a0df660
2016-11-08 14:58:07,216 INFO  [org.xdi.oxauth.auth.Authenticator] Authentication success for User: 'admin'
2016-11-08 14:58:12,046 INFO  [org.xdi.oxauth.auth.Authenticator] Authentication success for Client: '@!1D99.75E3.7043.4235!0001!757D.DC21!0008!E36B.A61A'
2016-11-08 14:58:17,255 INFO  [org.xdi.oxauth.auth.Authenticator] Authentication success for Client: '@!1D99.75E3.7043.4235!0001!757D.DC21!0008!E36B.A61A'
2016-11-08 14:58:22,704 INFO  [org.xdi.oxauth.auth.Authenticator] Authentication success for Client: '@!1D99.75E3.7043.4235!0001!757D.DC21!0008!E36B.A61A'
2016-11-08 14:58:28,042 INFO  [org.xdi.oxauth.auth.Authenticator] Authentication success for Client: '@!1D99.75E3.7043.4235!0001!757D.DC21!0008!E36B.A61A'
2016-11-08 14:58:33,525 INFO  [org.xdi.oxauth.auth.Authenticator] Authentication success for Client: '@!1D99.75E3.7043.4235!0001!757D.DC21!0008!E36B.A61A'
2016-11-08 14:58:38,529 INFO  [org.xdi.oxauth.auth.Authenticator] Authentication success for Client: '@!1D99.75E3.7043.4235!0001!757D.DC21!0008!E36B.A61A'
2016-11-08 14:58:43,423 INFO  [org.xdi.oxauth.auth.Authenticator] Authentication success for Client: '@!1D99.75E3.7043.4235!0001!757D.DC21!0008!E36B.A61A'
2016-11-08 14:58:48,437 INFO  [org.xdi.oxauth.auth.Authenticator] Authentication success for Client: '@!1D99.75E3.7043.4235!0001!757D.DC21!0008!E36B.A61A'
2016-11-08 14:58:53,310 INFO  [org.xdi.oxauth.auth.Authenticator] Authentication success for Client: '@!1D99.75E3.7043.4235!0001!757D.DC21!0008!E36B.A61A'
2016-11-08 14:58:58,177 INFO  [org.xdi.oxauth.auth.Authenticator] Authentication success for Client: '@!1D99.75E3.7043.4235!0001!757D.DC21!0008!E36B.A61A'
2016-11-08 14:59:03,545 INFO  [org.xdi.oxauth.auth.Authenticator] Authentication success for Client: '@!1D99.75E3.7043.4235!0001!757D.DC21!0008!E36B.A61A'

```

**Comment by yurem** [comment]
Yes, I think the problem in oxTrust. It can't work with this load balancer. Can we use http://ox.gluu.org/maven/org/xdi/oxauth-rp-demo/3.0.0-SNAPSHOT/oxauth-rp-demo-3.0.0-SNAPSHOT.war for testing?
