### ISSUE TITLE
Load test for 3.0.0 : POST https://m32xlarge.gluu.info/oxauth/login

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#385]
With 5 concurrent users oxauth works very well. If increase load to 100 concurrent users sometimes this exception is thrown.

https://github.com/GluuFederation/oxAuth/blob/master/jmeter/test/authorization_code_flow/Authorization%20Code%20Flow_amazon.jmx

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /oxauth/login. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
	at java.util.zip.GZIPInputStream.&lt;init&gt;(GZIPInputStream.java:79)
	at java.util.zip.GZIPInputStream.&lt;init&gt;(GZIPInputStream.java:91)
	at com.sun.faces.renderkit.ClientSideStateHelper.doGetState(ClientSideStateHelper.java:281)
	at com.sun.faces.renderkit.ClientSideStateHelper.getState(ClientSideStateHelper.java:244)
	at com.sun.faces.renderkit.ResponseStateManagerImpl.getState(ResponseStateManagerImpl.java:100)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.restoreView(FaceletViewHandlingStrategy.java:534)
	at com.sun.faces.application.view.MultiViewHandler.restoreView(MultiViewHandler.java:142)
	at org.jboss.seam.jsf.SeamViewHandler.restoreView(SeamViewHandler.java:194)
	at com.sun.faces.lifecycle.RestoreViewPhase.execute(RestoreViewPhase.java:192)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:116)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:593)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:199)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:74)
	at org.jboss.seam.web.RewriteFilter.process(RewriteFilter.java:98)
	at org.jboss.seam.web.RewriteFilter.doFilter(RewriteFilter.java:57)
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	at org.jboss.seam.web.IdentityFilter.doFilter(IdentityFilter.java:40)
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	at org.jboss.seam.web.LoggingFilter.doFilter(LoggingFilter.java:60)
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73)
	at org.jboss.seam.web.MultipartFilter.doFilter(MultipartFilter.java:90)
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	at org.jboss.seam.web.ExceptionFilter.doFilter(ExceptionFilter.java:64)
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	at org.jboss.seam.web.RedirectFilter.doFilter(RedirectFilter.java:45)
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	at org.jboss.seam.servlet.SeamFilter.doFilter(SeamFilter.java:158)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:523)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
</pre>
<hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.12.v20160915</a><hr/>

</body>
</html>

**Comment by yurem** [comment]
It's not clear why JSF is trying to restore state. We disabled JSF state at all:
```
<f:view transient="true">
```

As result login page contains:
```
<input type="hidden" name="javax.faces.ViewState" id="javax.faces.ViewState" value="stateless" autocomplete="off" />
```

In both our templates: https://github.com/GluuFederation/oxAuth/tree/master/Server/src/main/webapp/WEB-INF/incl/layout

Can you dump HTML which you get from server? Maybe there is page which not uses these templates.

Are you using latest CE 3.0.0 for testing?

**Comment by yuriyz** [comment]
@yurem ViewState is present, check it on https://m32xlarge.gluu.info I'm not sure it is very latest but it should be one of the latest. 
@sahiliamsso which exactly version do we have on https://m32xlarge.gluu.info ?

**Comment by yuriyz** [comment]
@yurem you are right, ViewState=stateless

Here is one of the samples of successful request
```
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>oxAuth - Login</title>
       <link type="text/css" rel="stylesheet" href="/oxauth/stylesheet/bootstrap.css" />
       <link type="text/css" rel="stylesheet" href="/oxauth/stylesheet/bootstrap-responsive.css" />
       <link type="text/css" rel="stylesheet" href="/oxauth/stylesheet/style.css" />
          <meta name="description" content="Gluu Inc." /></head><body>
    <div class="body"><div id="messages"></div>
          <header>
               <div class="container">
                    <div id="header" class="row-fluid">
                         <div class="logo span2"><div id="j_idt12">
                               	<a href="http://www.gluu.org/"><img src="img/logo.png" />
                                </a></div>
                         </div><!-- end logo-->

                         <div class="login span4 offset6">
                         Need a Gluu account?                         
                         <a class="register,need-account" href="../identity/register?redirectUri=https://support.gluu.org">Sign Up!</a>
                       	                        	 
                        </div>
                    </div>
               </div>

          </header>
          <!-- end header-->
          <div class="container">
               <div id="content" class="sign-in-page">
		        <div class="row-fluid">
<form id="loginForm" name="loginForm" method="post" action="/oxauth/login" class="signin-form span6 offset3" enctype="application/x-www-form-urlencoded">
<input type="hidden" name="loginForm" value="loginForm" />

				      <div class="inner-form-container row-fluid">
								<ul class="offset2 span10"><input type="hidden" name="javax.faces.FormSignature" value="eAqUINdJPE0a06XH/zaUVmPwM3o=" />
									<div class="row-fluid">
										<span class="input-name span3"><label for="loginForm:username">Username</label>
										</span>

										<div class="span6"><input id="loginForm:username" type="text" name="loginForm:username" autocomplete="off" />
										</div>
									</div>


									<div class="row-fluid">
										<span class="input-name span3"><label for="loginForm:password">Password</label>
										</span>
										<div class="span6"><input id="loginForm:password" type="password" name="loginForm:password" autocomplete="off" value="" />

										</div>
									</div>

									<li class="row-fluid submit-container">
										<div class="gradient contact-button green span2 offset3">
											<div id="submit_block" class="login_input"><input id="loginForm:loginButton" type="submit" name="loginForm:loginButton" value="Login" style="padding-left: 35%;" />
											</div>
											<span class="sprite-green_click_icon"></span>
										</div>
									</li>
									<li class="row-fluid submit-container"><div id="loginForm:registerId" style="display:none">
											<div class="gradient contact-button green span2 offset3">
												<div id="submit_block" class="login_input"><input id="loginForm:registerButton" type="submit" name="loginForm:registerButton" value="Register" style="padding-left: 35%;" />
												</div>
												<span class="sprite-green_click_icon"></span>
											</div></div></li>
									<li class="row-fluid">
										<div class="span9 offset3">
											<a class="need-account,register" href="/identity/person/passwordReminder.htm">Forgot your
												password?</a>
										</div>
									</li>
								</ul>

							</div><input type="hidden" name="javax.faces.ViewState" id="javax.faces.ViewState" value="stateless" autocomplete="off" />
</form>
                    </div>
               </div> 
               <div id="footer">
                    <p>Gluu, Inc,  |  Commercial use of support without express authorization is prohibited.</p>
               </div>                             
               </div>
               
            <script type="text/javascript">
            window.onload = function () {
                var userNameField = document.getElementById("loginForm:username");
                var passwordField = document.getElementById("loginForm:password");
                var userName = '';
                if (userName) {
                    userNameField.value = userName;
                    userNameField.readOnly = true;
                    passwordField.focus();
                } else {
                    userNameField.focus();
                }

                var displayRegister = false;
                if (displayRegister) {
                    var registerButton = document.getElementById("loginForm:registerId");
                    if (registerButton != null) {
                        registerButton.style.display = 'inline';
                    }
                }
            };
        </script>
    </div></body>
</html>
```

**Comment by yuriyz** [comment]
Resolved with file descriptor:
* soft nofile 65536
* hard nofile 262144
