### ISSUE TITLE
UMA AM validation in scenarion when oxauth behind te proxy

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#472]
With proxy we get error:
```
NFO   | jvm 1    | 2017/02/08 19:13:46 | 2017-02-08 19:13:46,284 ERROR [org.xdi.oxauth.service.uma.UmaValidationService] Get request for another AM: 'ce-release.gluu.org:443'
INFO   | jvm 1    | 2017/02/08 19:13:46 | 2017-02-08 19:13:46,285 DEBUG [org.xdi.oxauth.model.error.ErrorResponseFactory] Looking for the error with id: invalid_request
INFO   | jvm 1    | 2017/02/08 19:13:46 | 2017-02-08 19:13:46,285 DEBUG [org.xdi.oxauth.model.error.ErrorResponseFactory] Found error, id: invalid_request
INFO   | jvm 1    | 2017/02/08 19:13:46 | 2017-02-08 19:13:46,285 ERROR [xdi.oxauth.uma.ws.rs.CreateRptWS] Exception happened
INFO   | jvm 1    | 2017/02/08 19:13:46 | javax.ws.rs.WebApplicationException
INFO   | jvm 1    | 2017/02/08 19:13:46 |       at org.xdi.oxauth.service.uma.UmaValidationService.validateAmHost(UmaValidationService.java:84)
INFO   | jvm 1    | 2017/02/08 19:13:46 |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

In testing environment there are 2 servers:
1) cr-prev-version.gluu.org (Kong proxy)
2) ce-release.gluu.org (CE 2.4.4.3)

The flow is the next:
https://ce-prev-version.gluu.org:9443/ -> https://ce-release.gluu.org

In oxAuth configuration we changed token endpoint URL to point to proxy:
    "tokenEndpoint":"https://ce-prev-version.gluu.org:9443/oxauth/seam/resource/restv1/oxauth/token",

In the UMA metadata issuer is:
```
  "issuer" : "https://ce-release.gluu.org",
```

But it expects https://ce-prev-version.gluu.org

I think the proxy is just and intermidiary and real UMA AM is "https://ce-release.gluu.org"

Here is UMA configuration: https://ce-prev-version.gluu.org:9443/.well-known/uma-configuration

**Comment by yurem** [comment]
According to Mike:
>> I have been advising that the Gluu Server needs to be configured with the hostname of the load balancer.
>> for example, the discovery url should display the Load Balancer / Proxy hostname
because the client
never sees the backend hostname

Hence during adding API in order to correct RPT endpoint work we need to add parameter 'preserve_host=true' for proper UMA Client work
