### ISSUE TITLE
Failed to register client with custom attribute "oxAuthTrustedClient"

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#476]
```
2017-02-13 14:31:23,558 ERROR [qtp1100439041-19] [xdi.oxauth.register.ws.rs.RegisterRestWebServiceImpl] (RegisterRestWebServiceImpl.java:232) - Failed to persist entry: inum=@!1736.179E.AA60.16B2!0001!8F7C.B9AB!0008!6DAD.8CD1.E927.7015,ou=clients,o=@!1736.179E.AA60.16B2!0001!8F7C.B9AB,o=gluu
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to persist entry: inum=@!1736.179E.AA60.16B2!0001!8F7C.B9AB!0008!6DAD.8CD1.E927.7015,ou=clients,o=@!1736.179E.AA60.16B2!0001!8F7C.B9AB,o=gluu
	at org.gluu.site.ldap.persistence.LdapEntryManager.persist(LdapEntryManager.java:97) ~[oxLdap-3.0.0.jar:?]
	at org.gluu.site.ldap.persistence.AbstractEntryManager.persist(AbstractEntryManager.java:90) ~[oxLdap-3.0.0.jar:?]
	at org.xdi.oxauth.service.ClientService.persist(ClientService.java:76) ~[classes/:?]
....
Caused by: com.unboundid.ldap.sdk.LDAPException: attribute 'oxAuthTrustedClient' provided more than once
	at com.unboundid.ldap.sdk.LDAPConnection.add(LDAPConnection.java:1959) ~[unboundid-ldapsdk-3.2.0.jar:3.2.0]
	at com.unboundid.ldap.sdk.AbstractConnectionPool.add(AbstractConnectionPool.java:752) ~[unboundid-ldapsdk-3.2.0.jar:3.2.0]
```

**Comment by yurem** [comment]
Fixed
