### ISSUE TITLE
Custom Authentication (U2F, Super Gluu, Basic change password)  not working

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxAuth#599]
**Super Gluu**
Getting error after code is scanned in Super Gluu application
Super-Gluu. Authenticate for step 2. Failed to determine user name

**U2F**
Nothing happens when i click U2F key.
2017-08-02 22:16:17,676 INFO  [qtp242131142-16] [org.xdi.service.PythonService$PythonLoggerOutputStream] (PythonService.java:208) - U2F. Prepare for step 2. Call FIDO U2F in order to start registration workflow

**Basic Change Password**
I am not able to change password with BasicPassowrdUpdateExternalAuthenticator.py.

Enable Basic Change password custom screen
Try to change password, getting this error when click on update
![image](https://user-images.githubusercontent.com/21104811/28849474-c58af14c-7734-11e7-99ea-33979a6351a6.png)

Oxauth_Script logs
2017-08-01 22:10:34,857 INFO  [qtp242131142-11] [org.xdi.service.PythonService$PythonLoggerOutputStream] (PythonService.java:208) - Basic (with password update). Authenticate for step 2
2017-08-01 22:10:34,857 ERROR [qtp242131142-11] [org.xdi.oxauth.service.external.ExternalAuthenticationService] (ExternalAuthenticationService.java:167) - null
org.python.core.PyException: null
        at org.python.core.Py.TypeError(Py.java:259) ~[jython-2.7.0.jar:?]
        at org.python.core.PyReflectedFunction.throwError(PyReflectedFunction.java:209) ~[jython-2.7.0.jar:?]
        at org.python.core.PyReflectedFunction.throwBadArgError(PyReflectedFunction.java:312) ~[jython-2.7.0.jar:?]
        at org.python.core.PyReflectedFunction.throwError(PyReflectedFunction.java:321) ~[jython-2.7.0.jar:?]
        at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:167) ~[jython-2.7.0.jar:?]
        at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204) ~[jython-2.7.0.jar:?]
        at org.python.core.PyObject.__call__(PyObject.java:461) ~[jython-2.7.0.jar:?]
        at org.python.core.PyObject.__call__(PyObject.java:465) ~[jython-2.7.0.jar:?]

**Comment by sahiliamsso** [comment]
U2F is working fine on chrome.

**Comment by yurem** [comment]
I've updated Super Gluu script: https://github.com/GluuFederation/oxAuth/commit/a76585e1114431771d37b682cd776b9c4b3196fe

From my point of view basic password expiration not finished and requires rewrite. It's "nice' to see debug message in it and messages like "Hello World". Please open separate issue for this with Milestore 3.1.1. I've removed these messages: https://github.com/GluuFederation/oxAuth/commit/ab6bd2286cd634e7665657b649f3afc0a88274d8
The problem which not allows to test it not related to CE 3.1.0. It's in method "[newExpirationDate](https://github.com/GluuFederation/oxAuth/blob/master/Server/integrations/basic.password_expiration/PassowrdExpiration.py#L40)".
