### ISSUE TITLE
Cert authentication is broken

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxAuth#607]
![image](https://user-images.githubusercontent.com/21104811/29199324-58c530a0-7e3b-11e7-830d-85c39b6df73f.png)

2017-08-11 02:10:51,755 DEBUG [qtp242131142-13] [org.xdi.oxauth.service.external.ExternalAuthenticationService] (ExternalAuthenticationService.java:251) - Executing python 'getApiVersion' authenticator method
2017-08-11 02:10:51,756 DEBUG [qtp242131142-13] [org.xdi.oxauth.service.external.ExternalAuthenticationService] (ExternalAuthenticationService.java:225) - Executing python 'getExtraParametersForStep' authenticator method
2017-08-11 02:10:51,756 DEBUG [qtp242131142-13] [org.xdi.oxauth.service.external.ExternalAuthenticationService] (ExternalAuthenticationService.java:149) - Executing python 'getCountAuthenticationSteps' authenticator method
2017-08-11 02:10:51,757 ERROR [qtp242131142-13] [org.xdi.oxauth.service.external.ExternalAuthenticationService] (ExternalAuthenticationService.java:154) - null
org.python.core.PyException: null
        at org.python.core.Py.AttributeError(Py.java:205) ~[jython-2.7.0.jar:?]
        at org.python.core.PyObject.noAttributeError(PyObject.java:1013) ~[jython-2.7.0.jar:?]
        at org.python.core.PyObject.__getattr__(PyObject.java:1008) ~[jython-2.7.0.jar:?]
        at org.python.pycode._pyx8.getSessionAttribute$15(<iostream>:320) ~[?:?]
        at org.python.pycode._pyx8.call_function(<iostream>) ~[?:?]
        at org.python.core.PyTableCode.call(PyTableCode.java:167) ~[jython-2.7.0.jar:?]
        at org.python.core.PyBaseCode.call(PyBaseCode.java:153) ~[jython-2.7.0.jar:?]
        at org.python.core.PyFunction.__call__(PyFunction.java:423) ~[jython-2.7.0.jar:?]
        at org.python.core.PyMethod.__call__(PyMethod.java:141) ~[jython-2.7.0.jar:?]
        at org.python.pycode._pyx8.getCountAuthenticationSteps$11(<iostream>:264) ~[?:?]
        at org.python.pycode._pyx8.call_function(<iostream>) ~[?:?]
        at org.python.core.PyTableCode.call(PyTableCode.java:167) ~[jython-2.7.0.jar:?]
        at org.python.core.PyBaseCode.call(PyBaseCode.java:307) ~[jython-2.7.0.jar:?]
        at org.python.core.PyBaseCode.call(PyBaseCode.java:198) ~[jython-2.7.0.jar:?]
        at org.python.core.PyFunction.__call__(PyFunction.java:482) ~[jython-2.7.0.jar:?]
        at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237) ~[jython-2.7.0.jar:?]
        at org.python.core.PyMethod.__call__(PyMethod.java:228) ~[jython-2.7.0.jar:?]
        at org.python.core.PyMethod.__call__(PyMethod.java:218) ~[jython-2.7.0.jar:?]
        at org.python.core.PyMethod.__call__(PyMethod.java:213) ~[jython-2.7.0.jar:?]
        at org.python.core.PyObject._jcallexc(PyObject.java:3626) ~[jython-2.7.0.jar:?]
        at org.python.core.PyObject._jcall(PyObject.java:3658) ~[jython-2.7.0.jar:?]
        at org.python.proxies.__builtin__$PersonAuthentication$11.getCountAuthenticationSteps(Unknown Source) ~[?:?]
        at org.xdi.oxauth.service.external.ExternalAuthenticationService.executeExternalGetCountAuthenticationSteps(ExternalAuthenticationService.java:152) [classes/:?]
        at org.xdi.oxauth.service.external.ExternalAuthenticationService$Proxy$_$$_WeldSubclass.executeExternalGetCountAuthenticationSteps$$super(Unknown Source) [classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]

**Comment by yurem** [comment]
It works fine on dev server. Are you testing it on public server?
