### ISSUE TITLE
OpenID Dynamic Client Registration is failing

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#615]
I am seeing the following error in the logs on dynamic client registration.

```
Caused by: com.unboundid.ldap.sdk.LDAPException: objectClass: value #2 invalid per syntax
        at com.unboundid.ldap.sdk.LDAPConnection.add(LDAPConnection.java:1959) ~[unboundid-ldapsdk-3.2.0.jar:3.2.0]
        at com.unboundid.ldap.sdk.AbstractConnectionPool.add(AbstractConnectionPool.java:752) ~[unboundid-ldapsdk-3.2.0.jar:3.2.0]
        at com.unboundid.ldap.sdk.AbstractConnectionPool.add(AbstractConnectionPool.java:683) ~[unboundid-ldapsdk-3.2.0.jar:3.2.0]
        at org.gluu.site.ldap.OperationsFacade.addEntry(OperationsFacade.java:494) ~[oxcore-ldap-3.1.0-SNAPSHOT.jar:?]
```

But I wasn't able to get any more detail from LDAP about what attribute it is complaining about. Note: this registration request was working against version 3.0.

Here was the registration request:

```
 Attempting to register client: applicationType = web, clientName = World's Simplest Web App, redirectUris = [https://squid.gluu.info/cgi-bin/callback-login.cgi], isSecure = true, sectorIdentifierUri = , params = {
    "redirect_uris": ["https:\/\/squid.gluu.info\/cgi-bin\/callback-login.cgi"],
    "response_types": ["code"],
    "grant_types": ["authorization_code"],
    "application_type": "web",
    "contacts": ["bob@acme.us"],
    "client_name": "World's Simplest Web App",
    "default_acr_values": ["u2f"],
    "post_logout_redirect_uris": ["https:\/\/squid.gluu.info\/cgi-bin\/logout-confirmation.cgi"],
    "logout_uri": ["https:\/\/squid.gluu.info\/cgi-bin\/callback-logout.cgi"],
    "scopes": ["openid"]
}

```

**Comment by yurem** [comment]
Fixed: https://github.com/GluuFederation/community-edition-setup/commit/c7c804c982def82821bfd71d9cb259fd1288bf61

I updated oxAuth config to conform LDAP schema after custom client OC removal.
