### ISSUE TITLE
basic_multi_auth script not loading 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAuth#623]
Using script from: https://raw.githubusercontent.com/GluuFederation/oxAuth/version_3.0.2/Server/integrations/basic.multi_auth_conf/BasicMultiAuthConfExternalAuthenticator.py

Error from oxauth_script.log: 

```
2017-08-20 11:42:00,307 ERROR [oxAuthScheduler_Worker-3] [org.xdi.service.PythonService] (PythonService.java:150) - Failed to load python file
org.python.core.PyException: null
        at org.python.core.Py.ImportError(Py.java:328) ~[jython-2.7.0.jar:?]
        at org.python.core.imp.import_logic(imp.java:912) ~[jython-2.7.0.jar:?]
        at org.python.core.imp.import_module_level(imp.java:978) ~[jython-2.7.0.jar:?]
        at org.python.core.imp.importName(imp.java:1062) ~[jython-2.7.0.jar:?]
        at org.python.core.ImportFunction.__call__(__builtin__.java:1280) ~[jython-2.7.0.jar:?]
        at org.python.core.PyObject.__call__(PyObject.java:431) ~[jython-2.7.0.jar:?]
        at org.python.core.__builtin__.__import__(__builtin__.java:1232) ~[jython-2.7.0.jar:?]
        at org.python.core.imp.importFromAs(imp.java:1156) ~[jython-2.7.0.jar:?]
        at org.python.core.imp.importFrom(imp.java:1132) ~[jython-2.7.0.jar:?]
        at org.python.pycode._pyx5.f$0(<iostream>:23) ~[?:?]
        at org.python.pycode._pyx5.call_function(<iostream>) ~[?:?]
        at org.python.core.PyTableCode.call(PyTableCode.java:167) ~[jython-2.7.0.jar:?]
        at org.python.core.PyCode.call(PyCode.java:18) ~[jython-2.7.0.jar:?]
        at org.python.core.Py.runCode(Py.java:1386) ~[jython-2.7.0.jar:?]
        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296) ~[jython-2.7.0.jar:?]
        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:291) ~[jython-2.7.0.jar:?]
        at org.xdi.service.PythonService.loadPythonScript(PythonService.java:148) [oxcore-service-3.1.0-SNAPSHOT.jar:?]
        at org.xdi.service.PythonService$Proxy$_$$_WeldSubclass.loadPythonScript$$super(Unknown Source) [oxcore-service-3.1.0-SNAPSHOT.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.InvocationMonitor$InterceptorAction.proceed(InvocationMonitor.java:198) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.InvocationMonitor$InterceptorAction.proceed(InvocationMonitor.java:194) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.InvocationMonitor$Action.perform(InvocationMonitor.java:173) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.InvocationMonitor.monitor(InvocationMonitor.java:139) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:85) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:73) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:57) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.xdi.service.PythonService$Proxy$_$$_WeldSubclass.loadPythonScript(Unknown Source) [oxcore-service-3.1.0-SNAPSHOT.jar:?]
        at org.xdi.service.PythonService$Proxy$_$$_WeldClientProxy.loadPythonScript(Unknown Source) [oxcore-service-3.1.0-SNAPSHOT.jar:?]
        at org.xdi.service.custom.script.CustomScriptManager.createExternalTypeFromStringWithPythonException(CustomScriptManager.java:355) [oxcore-service-3.1.0-SNAPSHOT.jar:?]
        at org.xdi.service.custom.script.CustomScriptManager$Proxy$_$$_WeldSubclass.createExternalTypeFromStringWithPythonException(Unknown Source) [oxcore-service-3.1.0-SNAPSHOT.jar:?]
        at org.xdi.service.custom.script.CustomScriptManager.createExternalType(CustomScriptManager.java:329) [oxcore-service-3.1.0-SNAPSHOT.jar:?]
        at org.xdi.service.custom.script.CustomScriptManager.reloadCustomScriptConfigurations(CustomScriptManager.java:245) [oxcore-service-3.1.0-SNAPSHOT.jar:?]
        at org.xdi.service.custom.script.CustomScriptManager.reloadImpl(CustomScriptManager.java:151) [oxcore-service-3.1.0-SNAPSHOT.jar:?]
        at org.xdi.service.custom.script.CustomScriptManager.reload(CustomScriptManager.java:139) [oxcore-service-3.1.0-SNAPSHOT.jar:?]
        at org.xdi.service.custom.script.CustomScriptManager.reloadTimerEvent(CustomScriptManager.java:116) [oxcore-service-3.1.0-SNAPSHOT.jar:?]
        at org.xdi.service.custom.script.CustomScriptManager$Proxy$_$$_WeldSubclass.reloadTimerEvent$$super(Unknown Source) [oxcore-service-3.1.0-SNAPSHOT.jar:?]
        at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.InvocationMonitor$InterceptorAction.proceed(InvocationMonitor.java:198) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.InvocationMonitor$InterceptorAction.proceed(InvocationMonitor.java:194) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.InvocationMonitor$Action.perform(InvocationMonitor.java:173) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.InvocationMonitor.monitor(InvocationMonitor.java:139) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:85) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:73) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:57) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.xdi.service.custom.script.CustomScriptManager$Proxy$_$$_WeldSubclass.reloadTimerEvent(Unknown Source) [oxcore-service-3.1.0-SNAPSHOT.jar:?]
        at sun.reflect.GeneratedMethodAccessor110.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:129) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124) [cdi-api-2.0.jar:${parsedVersion.osgiVersion}]
        at org.jboss.weld.util.Observers.notify(Observers.java:166) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:159) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.manager.BeanManagerImpl.fireEvent(BeanManagerImpl.java:608) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.util.ForwardingBeanManager.fireEvent(ForwardingBeanManager.java:104) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.xdi.service.timer.TimerJob.execute(TimerJob.java:37) [oxcore-service-3.1.0-SNAPSHOT.jar:?]
        at org.xdi.service.timer.TimerJob$Proxy$_$$_WeldSubclass.execute$$super(Unknown Source) [oxcore-service-3.1.0-SNAPSHOT.jar:?]
        at sun.reflect.GeneratedMethodAccessor79.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.InvocationMonitor$InterceptorAction.proceed(InvocationMonitor.java:198) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.InvocationMonitor$InterceptorAction.proceed(InvocationMonitor.java:194) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.InvocationMonitor$Action.perform(InvocationMonitor.java:173) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.InvocationMonitor.monitor(InvocationMonitor.java:139) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:85) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:73) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:57) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.xdi.service.timer.TimerJob$Proxy$_$$_WeldSubclass.execute(Unknown Source) [oxcore-service-3.1.0-SNAPSHOT.jar:?]
        at org.xdi.service.timer.JobExecutionDelegate.execute(JobExecutionDelegate.java:29) [oxcore-service-3.1.0-SNAPSHOT.jar:?]
        at org.xdi.service.timer.JobExecutionDelegate$Proxy$_$$_WeldSubclass.execute$$super(Unknown Source) [oxcore-service-3.1.0-SNAPSHOT.jar:?]
        at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.InvocationMonitor$InterceptorAction.proceed(InvocationMonitor.java:198) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.InvocationMonitor$InterceptorAction.proceed(InvocationMonitor.java:194) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.InvocationMonitor$Action.perform(InvocationMonitor.java:173) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.InvocationMonitor.monitor(InvocationMonitor.java:139) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:85) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:73) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:57) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.xdi.service.timer.JobExecutionDelegate$Proxy$_$$_WeldSubclass.execute(Unknown Source) [oxcore-service-3.1.0-SNAPSHOT.jar:?]
        at org.xdi.service.timer.JobExecutionDelegate$Proxy$_$$_WeldClientProxy.execute(Unknown Source) [oxcore-service-3.1.0-SNAPSHOT.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.2.3.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.2.3.jar:?]
2017-08-20 11:42:00,350 ERROR [oxAuthScheduler_Worker-3] [org.xdi.service.custom.script.CustomScriptManager] (CustomScriptManager.java:331) - Failed to prepare external type 'org.xdi.exception.PythonException: Failed to load python file 'java.io.ByteArrayInputStream@cf845b2''

```

**Comment by yurem** [comment]
In 3.0.2 and 3.1.0 there are few incompatibilities. I added file with update instructions: https://github.com/GluuFederation/oxAuth/blob/master/Server/integrations/Migration_stepts_to_3.1.x.txt

Can you try script which conform this version https://github.com/GluuFederation/oxAuth/blob/master/Server/integrations/basic.multi_auth_conf/BasicMultiAuthConfExternalAuthenticator.py ?

**Comment by yurem** [comment]
@mzico can we close it?

**Comment by mzico** [comment]
@yurem sorry, I didn't get chance to retest this. Will complete testing by tomorrow.

**Comment by mzico** [comment]
@yurem : It's loading now.
