### ISSUE TITLE
Consent screen can throw NPE after timeout

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#627]
After authentication when user not answer in time on consent screen application throws NPE. According to stack trace it can't load session state:
```
java.lang.NullPointerException
	at org.xdi.oxauth.authorize.ws.rs.AuthorizeAction.permissionDenied(AuthorizeAction.java:696)
	at org.xdi.oxauth.authorize.ws.rs.AuthorizeAction$Proxy$_$$_WeldSubclass.permissionDenied(Unknown Source)
	at org.xdi.oxauth.authorize.ws.rs.AuthorizeAction.checkPermissionGranted(AuthorizeAction.java:167)
	at org.xdi.oxauth.authorize.ws.rs.AuthorizeAction$Proxy$_$$_WeldSubclass.checkPermissionGranted$$super(Unknown Source)
```

**Comment by yurem** [comment]
Fixed
