### ISSUE TITLE
Gluu 3.1.0 issues with memcached session persistence

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/oxAuth#646]
So I've been testing replication all day with Gluu 3.1.0 and Ubuntu 14. OxTrust and oxAuth failover doesn't work as session tokens aren't persisting. If I shut down every node, but the node I started with, I get this log of memcached failing to cache the token as it's "Non-serializable":

```
2017-09-15 19:53:41,609 ERROR [qtp2008017533-13]
[org.xdi.service.cache.MemcachedProvider] (MemcachedProvider.java:101)
- Failed to put object in cache, key:
{sha256Hex}eda00f0a7bbbf61a7a34e0de93468ff9f0a28e64efaa517617fc7e5363f16564
java.lang.IllegalArgumentException: Non-serializable object
        at
net.spy.memcached.transcoders.BaseSerializingTranscoder.serialize(BaseSerializingTranscoder.java:110)
~[spymemcached-2.12.2.jar:2.12.2]
        at
net.spy.memcached.transcoders.SerializingTranscoder.encode(SerializingTranscoder.java:162)
~[spymemcached-2.12.2.jar:2.12.2]
        at
net.spy.memcached.MemcachedClient.asyncStore(MemcachedClient.java:304)
~[spymemcached-2.12.2.jar:2.12.2]
        at
net.spy.memcached.MemcachedClient.set(MemcachedClient.java:928)
~[spymemcached-2.12.2.jar:2.12.2]
        at
org.xdi.service.cache.MemcachedProvider.put(MemcachedProvider.java:97)
[oxcore-service-3.1.0.Final.jar:?]
        at
org.xdi.service.cache.CacheProvider$Proxy$_$$_WeldClientProxy.put(Unknown
Source) [oxcore-service-3.1.0.Final.jar:?]
        at org.xdi.service.CacheService.put(CacheService.java:41)
[oxcore-service-3.1.0.Final.jar:?]
        at
org.xdi.service.CacheService$Proxy$_$$_WeldClientProxy.put(Unknown
Source) [oxcore-service-3.1.0.Final.jar:?]
        at
org.xdi.oxauth.service.GrantService.persist(GrantService.java:129)
[classes/:?]
        at
org.xdi.oxauth.model.common.AuthorizationGrant.persist(AuthorizationGrant.java:179)
[classes/:?]
        at
org.xdi.oxauth.model.common.AuthorizationGrant.createIdToken(AuthorizationGrant.java:164)
[classes/:?]
        at
org.xdi.oxauth.token.ws.rs.TokenRestWebServiceImpl.requestAccessToken(TokenRestWebServiceImpl.java:176)
[classes/:?]
        at
org.xdi.oxauth.token.ws.rs.TokenRestWebServiceImpl$Proxy$_$$_WeldClientProxy.requestAccessToken(Unknown
Source) [classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~[?:1.8.0_112]
        at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
~[?:1.8.0_112]
        at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at
org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
[resteasy-jaxrs-3.0.21.Final.jar:3.0.21.Final]
        at
org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
[resteasy-jaxrs-3.0.21.Final.jar:3.0.21.Final]
        at
org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
[resteasy-jaxrs-3.0.21.Final.jar:3.0.21.Final]
        at
org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
[resteasy-jaxrs-3.0.21.Final.jar:3.0.21.Final]
        at
org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
[resteasy-jaxrs-3.0.21.Final.jar:3.0.21.Final]
        at
org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
[resteasy-jaxrs-3.0.21.Final.jar:3.0.21.Final]
        at
org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228)
[resteasy-jaxrs-3.0.21.Final.jar:3.0.21.Final]
        at
org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
[resteasy-jaxrs-3.0.21.Final.jar:3.0.21.Final]
        at
org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
[resteasy-jaxrs-3.0.21.Final.jar:3.0.21.Final]
        at
javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
[servlet-api-3.1.jar:3.1.0]
        at
org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
[jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
[jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:193)
[websocket-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
[jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
[rewrite-servlet-3.4.1.Final.jar:3.4.1.Final]
        at
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
[jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.xdi.oxauth.audit.debug.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:55)
[classes/:?]
        at
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1751)
[jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.xdi.oxauth.auth.AuthenticationFilter.processBasicAuth(AuthenticationFilter.java:212)
[classes/:?]
        at
org.xdi.oxauth.auth.AuthenticationFilter.doFilter(AuthenticationFilter.java:102)
[classes/:?]
        at
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
[jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.gluu.oxserver.filters.AbstractCorsFilter.handleNonCORS(AbstractCorsFilter.java:343)
[oxcore-server-3.1.0.Final.jar:?]
        at
org.gluu.oxserver.filters.AbstractCorsFilter.doFilter(AbstractCorsFilter.java:120)
[oxcore-server-3.1.0.Final.jar:?]
        at
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
[jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
[jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
[jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
[jetty-security-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
[jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
[jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
[jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
[jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
[jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
[jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
[jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
[jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
[jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.Server.handle(Server.java:534)
[jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
[jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
[jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
[jetty-io-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
[jetty-io-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
[jetty-io-9.3.15.v20161220.jar:9.3.15.v20161220]
 at
org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
[jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
[jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
[jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
[jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
        at
org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
[jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.io.NotSerializableException: org.xdi.oxauth.model.ldap.TokenLdap
        at
java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
~[?:1.8.0_112]
        at
java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
~[?:1.8.0_112]
        at
net.spy.memcached.transcoders.BaseSerializingTranscoder.serialize(BaseSerializingTranscoder.java:105)
~[spymemcached-2.12.2.jar:2.12.2]
        ... 64 more
2017-09-15 19:54:34,394 INFO  [Thread-62]
[org.xdi.oxauth.model.config.ConfigurationFactory]
(ConfigurationFactory.java:321) - Loading configuration from LDAP...
2017-09-15 19:54:34,470 INFO  [Thread-62]
[org.xdi.oxauth.service.AppInitializer] (AppInitializer.java:595) -
Setting loggers level to: 'DEFAULT'
2017-09-15 19:54:34,470 INFO  [Thread-62]
[org.xdi.oxauth.service.AppInitializer] (AppInitializer.java:600) -
Reloading log4j configuration
2017-09-15 19:55:29,240 ERROR [qtp2008017533-18]
[org.xdi.oxauth.auth.Authenticator] (Authenticator.java:451) - Failed
to get attributes from session
```

**Comment by nynymike** [comment]
We need to look into this...

**Comment by yuriyz** [comment]
checking ...

**Comment by yuriyz** [comment]
Fixed
