### ISSUE TITLE
OIDC authorization page throws an error

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#672]
Environment:
Ubuntu 14.04, gluu-server-3.1.1-1.7

Preconditions:
1. A working OIDC setup using your Gluu instance as OP

Steps to reproduce:
1. Log in to web UI as admin
2. Edit your test client's properties at Gluu, disabling Pre-Authorization
3. Start any OIDC flow using this client

Result:
An "Error Encountered An unexpected error has occured" page is displayed and Java exception is logged in `oxauth.log` (full text [here](https://github.com/GluuFederation/oxAuth/files/1384282/authz-page-error.txt)):
```
2017-10-14 00:31:40,933 ERROR [qtp2008017533-13] [org.xdi.oxauth.exception.GlobalExceptionHandler] (GlobalExceptionHandler.java:45) - //opt/jetty-9.3/temp/jetty-localhost-8081-oxauth.war-_oxauth-any-2913699815801948513.dir/webapp/WEB-INF/incl/layout/authorize-template.xhtml: Property 'getCssLocation' not found on type org.xdi.oxauth.service.OxAuthConfigurationService
javax.el.ELException: //opt/jetty-9.3/temp/jetty-localhost-8081-oxauth.war-_oxauth-any-2913699815801948513.dir/webapp/WEB-INF/incl/layout/authorize-template.xhtml: Property 'getCssLocation' not found on type org.xdi.oxauth.service.OxAuthConfigurationService
	at com.sun.faces.facelets.compiler.AttributeInstruction.write(AttributeInstruction.java:94) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.compiler.UIInstructions.encodeBegin(UIInstructions.java:82) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.compiler.UILeaf.encodeAll(UILeaf.java:183) ~[jsf-impl-2.2.14.jar:2.2.14]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859) ~[jsf-api-2.2.14.jar:2.2]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859) ~[jsf-api-2.2.14.jar:2.2]
```

**Comment by aliaksander-samuseu** [comment]
Fixed
