### ISSUE TITLE
UMA RPT policy script for SCIM crashes

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxAuth#692]
Previously working script SCIM protection by UMA is failing. The following is obtained in the oxAuth logs when the `uma_client_authz_rpt_policy` script is executed
```
...
TRACE xdi.oxauth.auth.Authenticator Authenticator.java:148- Authentication successfully for '@!3245.DF39.6A34.9E97!0001!513A.9888!0008!E840.E4F0'
DEBUG token.ws.rs.TokenRestWebServiceImpl TokenRestWebServiceImpl.java:98- Attempting to request access token: grantType = urn:ietf:params:oauth:grant-type:uma-ticket, code = null, redirectUri = null, username = null, refreshToken = null, clientId = null, ExtraParams = {client_assertion_type=[urn:ietf:params:oauth:client-assertion-type:jwt-bearer], ticket=[d633cfbc-33a0-4cf2-ae4e-2d45d9e20553], client_assertion=[eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzM4NCIsImtpZCI6ImY5ZjQwMzUzLTk2NjItNGZiMi1hNWU5LTE3ZWU1N2FkMzFjZiJ9.eyJpc3MiOiJAITMyNDUuREYzOS42QTM0LjlFOTchMDAwMSE1MTNBLjk4ODghMDAwOCFFODQwLkU0RjAiLCJzdWIiOiJAITMyNDUuREYzOS42QTM0LjlFOTchMDAwMSE1MTNBLjk4ODghMDAwOCFFODQwLkU0RjAiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo4NDQzL294YXV0aC9yZXN0djEvdG9rZW4iLCJqdGkiOiI5NjE2ZTVlNi05ZTU5LTRhNjAtYTJlMC01YmZlODZmNWU5N2MiLCJleHAiOjE1MTA0MDg2NjUsImlhdCI6MTUxMDQwODM2NX0.MGUCMFklwDk0n0l4U9Bnynmhl8XtIffjbDGXUjwD5Q3-9isyMOzsNDAg9bNL7zju3G2JiQIxAMRhkRKcRRCJ2HfQmlXUACmMuwGqtCyEJHlMDXN8AmvFbVGu3L3DGiEQKqqdIoEwqg], grant_type=[urn:ietf:params:oauth:grant-type:uma-ticket]}, isSecure = true, codeVerifier = null, ticket = d633cfbc-33a0-4cf2-ae4e-2d45d9e20553
TRACE oxauth.uma.service.UmaTokenService UmaTokenService.java:79- requestRpt grant_type: urn:ietf:params:oauth:grant-type:uma-ticket, ticket: d633cfbc-33a0-4cf2-ae4e-2d45d9e20553, claim_token: null, claim_token_format: null, pct: null, rpt: null, scope: null
TRACE oxauth.uma.service.UmaValidationService UmaValidationService.java:207- Validate grantType: urn:ietf:params:oauth:grant-type:uma-ticket
TRACE oxauth.uma.service.UmaValidationService UmaValidationService.java:370- CandidateGrantedScopes: scim_access
TRACE oxauth.uma.service.UmaPctService UmaPctService.java:81- PCT code: a58cb0d9-3b2f-4407-9909-0b959cdda995_50BA.12BD.1EB3.F8EF.22A2.351A.26F1.609F, claims: {}
DEBUG oxauth.service.external.ExternalUmaRptPolicyService ExternalUmaRptPolicyService.java:107- Executing python 'getRequiredClaims' method, script: uma_client_authz_rpt_policy
DEBUG oxauth.service.external.ExternalUmaRptPolicyService ExternalUmaRptPolicyService.java:109- python 'getRequiredClaims' result: []
DEBUG oxauth.service.external.ExternalUmaRptPolicyService ExternalUmaRptPolicyService.java:119- Executing python 'getClaimsGatheringScriptName' method, script: uma_client_authz_rpt_policy
...
DEBUG oxauth.service.external.ExternalUmaRptPolicyService ExternalUmaRptPolicyService.java:95- Executing python 'authorize' method, script: uma_client_authz_rpt_policy
ERROR oxauth.service.external.ExternalUmaRptPolicyService ExternalUmaRptPolicyService.java:100- Failed to execute python 'authorize' method, script: uma_client_authz_rpt_policy, message: null
org.python.core.PyException: null
	at org.python.core.Py.AttributeError(Py.java:205) ~[jython-2.7.0.jar:?]
	at org.python.core.PyObject.noAttributeError(PyObject.java:1013) ~[jython-2.7.0.jar:?]
	at org.python.core.PyObject.object___getattribute__(PyObject.java:3816) ~[jython-2.7.0.jar:?]
	at org.python.core.PyObject$object___getattribute___exposer.__call__(Unknown Source) ~[jython-2.7.0.jar:?]
	at org.python.core.Deriveds.__findattr_ex__(Deriveds.java:59) ~[jython-2.7.0.jar:?]
	at org.python.core.PyObjectDerived.__findattr_ex__(PyObjectDerived.java:1036) ~[jython-2.7.0.jar:?]
	at org.python.core.PyObject.__getattr__(PyObject.java:1006) ~[jython-2.7.0.jar:?]
	at org.python.pycode._pyx11.authorize$7(<iostream>:67) ~[?:?]
...
52:46 TRACE oxauth.uma.service.UmaTokenService UmaTokenService.java:102- Policy script inum: '@!3245.DF39.6A34.9E97!0001!513A.9888!0011!2DAF.F9A5' result: 'false'
52:46 TRACE oxauth.uma.service.UmaTokenService UmaTokenService.java:104- Stop authorization scriptMap execution, current script returns false, script inum: @!3245.DF39.6A34.9E97!0001!513A.9888!0011!2DAF.F9A5
```

Apparently, it cannot retrieve the `client_id`, thus, authorization fails.

**Comment by yuriyz** [comment]
In script there seems to be these lines, not sure where it goes in weird state there 
```
  identity = CdiUtil.bean(Identity)
  client_id = identity.getSessionClient().getClient().getClientId()
```

But you can get client directly from authorization context
```
context.getClient().getClientId();
```

@jgomer2001 please try it. If it will not work, please give source of your script (to make sure it's not modified) and full oxauth.log file. 

Closing, please reopen if issue will occur.

**Comment by jgomer2001** [comment]
Thanks! it was my planned workaround for this issue. Script [updated](https://github.com/GluuFederation/oxAuth/commit/1a7e8357315f6b9e9d3a0e7d74f4a02ed2b2ac98). Problem not being presented now.

**Comment by jgomer2001** [comment]
Also added method `getClaimsGatheringScriptName` (if missing it provokes unnecessary errors logged. See https://support.gluu.org/identity-management/4763/uma2scim-errors-on-insert-with-sample-code-getclaimsgatheringscriptname-script-method-return-null-or-blank-value-script-uma_client_authz_rpt_policy/)

**Comment by sahiliamsso** [comment]
Changes are not reflected in 3.1.2

**Comment by jgomer2001** [comment]
Script was fixed in oxAuth and not transferred to community-edition
https://github.com/GluuFederation/community-edition-setup/commit/f2bc7c2e762d639cfce486d44a14b77f5b9d649a
