### ISSUE TITLE
UMA 2 : Fix NPE if required claims_redirect_uri is not passed

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#826]
2018-06-19 10:25:47,353 ERROR [qtp1190524793-25] [org.xdi.oxauth.uma.service.UmaGatherer] (UmaGatherer.java:124) - Exception during gather() method call.
java.lang.NullPointerException: null
	at org.xdi.oxauth.uma.service.UmaGatherer.addQueryParameter(UmaGatherer.java:160) ~[classes/:?]
	at org.xdi.oxauth.uma.service.UmaGatherer.constructRedirectUri(UmaGatherer.java:143) ~[classes/:?]
	at org.xdi.oxauth.uma.service.UmaGatherer.onSuccess(UmaGatherer.java:135) ~[classes/:?]
	at org.xdi.oxauth.uma.service.UmaGatherer.gather(UmaGatherer.java:120) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]

**Comment by yuriyz** [comment]
Fixed in 3.1.4 and master.
