### ISSUE TITLE
Cert authentication failing

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxAuth#904]
Getting this error when cert authentication is enabled

java.lang.Exception: Using default external type class 	at org.xdi.service.custom.script.CustomScriptManager.createExternalType(CustomScriptManager.java:349) 	at org.xdi.service.custom.script.CustomScriptManager.reloadCustomScriptConfigurations(CustomScriptManager.java:253) 	at org.xdi.service.custom.script.CustomScriptManager.reloadImpl(CustomScriptManager.java:153) 	at org.xdi.service.custom.script.CustomScriptManager.reload(CustomScriptManager.java:141) 	at org.xdi.service.custom.script.CustomScriptManager.reloadTimerEvent(CustomScriptManager.java:118) 	at org.xdi.service.custom.script.CustomScriptManager$Proxy$_$$_WeldSubclass.reloadTimerEvent(Unknown Source) 	at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498) 	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95) 	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85) 	at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:129) 	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330) 	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308) 	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286) 	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124) 	at org.jboss.weld.util.Observers.notify(Observers.java:166) 	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285) 	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273) 	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177) 	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:159) 	at org.jboss.weld.manager.BeanManagerImpl.fireEvent(BeanManagerImpl.java:632) 	at org.jboss.weld.util.ForwardingBeanManager.fireEvent(ForwardingBeanManager.java:104) 	at org.xdi.service.timer.TimerJob.execute(TimerJob.java:37) 	at org.xdi.service.timer.JobExecutionDelegate.execute(JobExecutionDelegate.java:29) 	at org.xdi.service.timer.JobExecutionDelegate$Proxy$_$$_WeldClientProxy.execute(Unknown Source) 	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) 	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
--

**Comment by yurem** [comment]
Can you attach full stack trace from logs?

**Comment by willow9886** [comment]
@sahiliamsso can you provide?

**Comment by sahiliamsso** [comment]
It worked fine after generating certs and importing in chrome browser.

**Comment by yurem** [comment]
@sahiliamsso can you check if current integration documentation is up to date:
https://github.com/GluuFederation/oxAuth/blob/master/Server/integrations/cert/Generate%20cert%20server%20guide.txt
and
https://github.com/GluuFederation/oxAuth/blob/master/Server/integrations/cert/Demo%20Configuration.md
