### ISSUE TITLE
Sign token introspection response

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#947]
We need an option to provide a signature for the token introspection response.

**Comment by yuriyz** [comment]
Done. Added new request parameter `response_as_jwt` - OPTIONAL. Boolean value with default value false. If true, returns introspection response as JWT (signed based on client configuration used for authentication to Introspection Endpoint).
Docs updated.

**Comment by sahiliamsso** [comment]
I am getting this error, Please check it,
```
curl -vvv --request POST   --url https://autoqa.gluu.org/oxauth/restv1/introspection   --header 'accept: application/json'   --header 'authorization: Basic ZDc1ODhlMzUtZTkzYy00OTExLWJmMTktMjY5YjQwNDVmZmIzOmZpcmV3YWxs'   --data 'token=fe62eaef-cc6c-4a27-98f8-b7bea602a67b&response_as_jwt=true'
* About to connect() to autoqa.gluu.org port 443 (#0)
*   Trying 127.0.1.1...
* Connected to autoqa.gluu.org (127.0.1.1) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=autoqa.gluu.org
*       start date: Jun 19 13:36:20 2019 GMT
*       expire date: Sep 17 13:36:20 2019 GMT
*       common name: autoqa.gluu.org
*       issuer: CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US
> POST /oxauth/restv1/introspection HTTP/1.1
> User-Agent: curl/7.29.0
> Host: autoqa.gluu.org
> accept: application/json
> authorization: Basic ZDc1ODhlMzUtZTkzYy00OTExLWJmMTktMjY5YjQwNDVmZmIzOmZpcmV3YWxs
> Content-Length: 63
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 63 out of 63 bytes
< HTTP/1.1 500 Server Error
< Date: Thu, 20 Jun 2019 02:56:29 GMT
< Server: Jetty(9.4.12.v20180830)
< X-Xss-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< Content-Type: application/json
< Content-Length: 0
< Connection: close
<
* Closing connection 0

```


```
2019-06-20 02:55:30,740 ERROR [qtp985655350-19] [gluu.oxauth.introspection.ws.rs.IntrospectionWebService] (IntrospectionWebService.java:175) - null
java.lang.NullPointerException: null
        at org.gluu.oxauth.model.common.AuthorizationGrant.getSub(AuthorizationGrant.java:354) ~[classes/:?]
        at org.gluu.oxauth.introspection.ws.rs.IntrospectionWebService.introspect(IntrospectionWebService.java:138) ~[classes/:?]
        at org.gluu.oxauth.introspection.ws.rs.IntrospectionWebService.introspectPost(IntrospectionWebService.java:104) ~[classes/:?]
        at org.gluu.oxauth.introspection.ws.rs.IntrospectionWebService$Proxy$_$$_WeldClientProxy.introspectPost(Unknown Source) ~[classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140) ~[resteasy-jaxrs-3.5.1.Final.jar:3.5.1.Final]
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:510) ~[resteasy-jaxrs-3.5.1.Final.jar:3.5.1.Final]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:401) ~[resteasy-jaxrs-3.5.1.Final.jar:3.5.1.Final]
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:365) ~[resteasy-jaxrs-3.5.1.Final.jar:3.5.1.Final]
```

**Comment by yuriyz** [comment]
It seems your client doesn't have `redirect_uri`, anyway, NPE fixed, please re-test.
