### ISSUE TITLE
Fix expired entries clean up

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#969]
oxAuth logs should have next exception which identify this issue:
```
Caused by: LDAPException(resultCode=81 (server down), numEntries=0, numReferences=0, errorMessage='Failed to scroll to specified startIndex', ldapSDKVersion=4.0.7, revision=28484')
    at org.gluu.site.ldap.OperationsFacade.search(OperationsFacade.java:329)
    at org.gluu.site.ldap.persistence.LdapEntryManager.findEntries(LdapEntryManager.java:399)
```

**Comment by yurem** [comment]
Fixed
